### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jumski** [github/hub#1002]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
github.com/github/hub/github.(*Project).WebURL(0x0, 0x0, 0x0, 0x0, 0x0, 0xc208032300, 0xe, 0x0, 0x0)
	/home/vagrant/gocode/src/github.com/github/hub/github/project.go:30 +0x91f
github.com/github/hub/commands.compare(0xa86020, 0xc208058090)
	/home/vagrant/gocode/src/github.com/github/hub/commands/compare.go:78 +0x264
github.com/github/hub/commands.(*Command).Call(0xa86020, 0xc208058090, 0x0, 0x0)
	/home/vagrant/gocode/src/github.com/github/hub/commands/commands.go:47 +0x184
github.com/github/hub/commands.(*Runner).Call(0xc20802c880, 0xa86020, 0xc208058090, 0x0, 0x0, 0x0)
	/home/vagrant/gocode/src/github.com/github/hub/commands/runner.go:90 +0x54
github.com/github/hub/commands.(*Runner).Execute(0xc20802c880, 0x0, 0x0, 0x0)
	/home/vagrant/gocode/src/github.com/github/hub/commands/runner.go:82 +0x215
main.main()
	/home/vagrant/gocode/src/github.com/github/hub/main.go:12 +0x40

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

**Comment by jumski** [comment]
oh crap, this was not the github repo, sorry for that :)

closing

**Comment by jumski** [comment]
maybe worth adding a helpful message if run from non-github repo tho

**Comment by mislav** [comment]
Hi thanks for the report. Sorry that you've experienced a crash. Even if your local repo was not cloned from GitHub, we'd still like to know more details so we can fix the error and make a nicer error message.

What arguments did you use for `hub compare`? Which `git remote -v` were available? (You can anonymize the actual repo names.)

**Comment by jumski** [comment]
I've just used bare `hub compare` without any arguments.

Repos available:

```
origin  git@bitbucket.org:xxx/yyy.git (fetch)
origin  git@bitbucket.org:xxx/yyy.git (push)
```

Thanks

**Comment by mislav** [comment]
Thanks! Which `hub version`?

**Comment by mislav** [comment]
Nevermind; I managed to reproduce the error! Fix pending! Thanks

**Comment by jumski** [comment]
for brevity:

```
git version 2.5.3
hub version 2.2.1
```

cheers
