### ISSUE TITLE
hub am errors "wrong number of arguments"

### ISSUE THREAD

**Issue by samdark** [github/hub#1013]
```
hub am https://github.com/yiisoft/yii2/pull/9941
/usr/local/bin/hub:75:in `initialize': wrong number of arguments (9 for 1) (ArgumentError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1030:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1030:in `proxy_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1017:in `proxy?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:868:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /usr/local/bin/hub:473:in `perform_request'
	from /usr/local/bin/hub:588:in `perform_request'
	from /usr/local/bin/hub:418:in `get'
	from /usr/local/bin/hub:329:in `pullrequest_patch'
	from /usr/local/bin/hub:1958:in `am'
	from /usr/local/bin/hub:1586:in `run'
	from /usr/local/bin/hub:2508:in `initialize'
	from /usr/local/bin/hub:2512:in `new'
	from /usr/local/bin/hub:2512:in `execute'
	from /usr/local/bin/hub:2563:in `<main>'
```

**Comment by mislav** [comment]
Hi, you seem to be using a really old version of hub. Can you try with the newest version? On Mac, it's easily installable with Homebrew: `brew upgrade hub`. Then verify `hub version` is at least 2.2. Then ping us back! Thanks

**Comment by samdark** [comment]
I'm not using brew. I think I'm using the one I build from `master` branch.

**Comment by mislav** [comment]
I understand. You still have the old version, though. Installing from Homebrew would give you the latest release. Or you can build from master again, but you will need Go compiler. You can also download the [latest precompiled binary for OS X](https://github.com/github/hub/releases).

Let me know if that worked

**Comment by samdark** [comment]
Worked. I was copying to wrong `bin`. My fault.

**Comment by seanmakesgames** [comment]
Just hit this using brew. Uninstalled and reinstalled hub from brew and the hub version is still 1.12

**Comment by seanmakesgames** [comment]
`brew update` solved the issue.

**Comment by benmathes** [comment]
I came across this same error:
```shell
=> hub create                                                                                                                                                                                                                                                                 
/usr/local/bin/hub:74:in `initialize': wrong number of arguments (9 for 1) (ArgumentError)                                                                                                                                                                                    
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1030:in `new'                                                                                                                                                              
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1030:in `proxy_uri'                                                                                                                                                        
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1017:in `proxy?'                                                                                                                                                           
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:868:in `connect'                                                                                                                                                           
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'                                                                                                                                                          
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'                                                                                                                                                             
        from /usr/local/bin/hub:451:in `perform_request'                                                                                                                                                                                                                      
        from /usr/local/bin/hub:566:in `perform_request'                                                                                                                                                                                                                      
        from /usr/local/bin/hub:411:in `get'                                                                                                                                                                                                                                  
        from /usr/local/bin/hub:291:in `repo_info'                                                                                                                                                                                                                            
        from /usr/local/bin/hub:296:in `repo_exists?'                                                                                                                                                                                                                         
        from /usr/local/bin/hub:2017:in `create'                                                                                                                                                                                                                              
        from /usr/local/bin/hub:1560:in `run'                                                                                                                                                                                                                                 
        from /usr/local/bin/hub:2480:in `initialize'                                                                                                                                                                                                                          
        from /usr/local/bin/hub:2484:in `new'                                                                                                                                                                                                                                 
        from /usr/local/bin/hub:2484:in `execute'                                                                                                                                                                                                                             
        from /usr/local/bin/hub:2535:in `<main>'
```


And I thought I had the latest `hub`:
```shell
=> brew upgrade hub                                                                                                                                                                                                                                                           
Error: hub 2.2.3 already installed
```

But my symlink was pointing to the old version!
```shell
=> ls -al $(which hub)                                                                                                                                                                                                                                                       
lrwxr-xr-x  1 benmathes  admin  28 Mar 29 09:40 /usr/local/bin/hub -> ../Cellar/hub/1.12.0/bin/hub 
```

Which was fixed by: `brew uninstall --force hub; brew update; brew install hub`

Now the symlink is correct (note the 2.2.3 in the symlink target):
```shell
=> ls -al $(which hub)                                                                                                                                                                                                                                                        
lrwxr-xr-x  1 benmathes  admin  27 Mar 29 10:00 /usr/local/bin/hub -> ../Cellar/hub/2.2.3/bin/hub
```

and now `hub create` works.
