### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by port-kentaro-honda** [github/hub#1042]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
github.com/github/hub/commands.fork(0x721e80, 0xc8200a6240)
	/var/folders/08/6djc5fjs7gq20zv_1gx0_c3w0000gn/T/go/src/github.com/github/hub/commands/fork.go:75 +0x396
github.com/github/hub/commands.(*Command).Call(0x721e80, 0xc8200a6240, 0x0, 0x0)
	/var/folders/08/6djc5fjs7gq20zv_1gx0_c3w0000gn/T/go/src/github.com/github/hub/commands/commands.go:47 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc820065920, 0x721e80, 0xc8200a6240, 0x0, 0x0, 0x0)
	/var/folders/08/6djc5fjs7gq20zv_1gx0_c3w0000gn/T/go/src/github.com/github/hub/commands/runner.go:93 +0x5a
github.com/github/hub/commands.(*Runner).Execute(0xc820065920, 0x0, 0x0, 0x0)
	/var/folders/08/6djc5fjs7gq20zv_1gx0_c3w0000gn/T/go/src/github.com/github/hub/commands/runner.go:85 +0x367
main.main()
	/private/tmp/hub20151119-59033-n5wdgh/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.3.2 (Apple Git-55)
hub version 2.2.0-g1202fc4
```

**Comment by mislav** [comment]
Thanks for reporting!

@jingweno Probably a case of [missing origin remote](https://github.com/github/hub/blob/1202fc4d391a8705dab93832b26e032a13837b03/commands/fork.go#L74-L75)?

**Comment by jingweno** [comment]
@mislav Yeah, we'd need to check the error at https://github.com/github/hub/blob/1202fc4d391a8705dab93832b26e032a13837b03/commands/fork.go#L74 which the `error` is ignored...
