### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by johnsyweb** [github/hub#1101]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
github.com/github/hub/github.(*Project).WebURL(0x0, 0x0, 0x0, 0x0, 0x0, 0xc20800bf20, 0x13, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/github/project.go:30 +0x91f
github.com/github/hub/commands.compare(0x68aa20, 0xc20805a090)
	/tmp/go/src/github.com/github/hub/commands/compare.go:78 +0x264
github.com/github/hub/commands.(*Command).Call(0x68aa20, 0xc20805a090, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x184
github.com/github/hub/commands.(*Runner).Call(0xc20802a880, 0x68aa20, 0xc20805a090, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:90 +0x54
github.com/github/hub/commands.(*Runner).Execute(0xc20802a880, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:82 +0x215
main.main()
	/private/tmp/hub20150621-19614-1vln7lw/hub-2.2.1/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

**Comment by mislav** [comment]
Could you upgrade to hub 2.2.3?

**Comment by johnsyweb** [comment]
Probably. It transpires that I was running `git compare` in a local repo without a `github.com` remote.

**Comment by mislav** [comment]
Fixed in https://github.com/github/hub/pull/1044
