### ISSUE TITLE
Hub create is not assigning remote properly

### ISSUE THREAD

**Issue by Edozie101** [github/hub#1132]
After trying to use hub create, it crashes and doesn't assign a remote at all .

This is the error brought up after using hub create. 

````
hub create
/usr/local/bin/hub:75:in `initialize': wrong number of arguments (9 for 1) (ArgumentError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1030:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1030:in `proxy_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1017:in `proxy?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:868:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /usr/local/bin/hub:473:in `perform_request'
	from /usr/local/bin/hub:588:in `perform_request'
	from /usr/local/bin/hub:418:in `get'
	from /usr/local/bin/hub:292:in `repo_info'
	from /usr/local/bin/hub:297:in `repo_exists?'
	from /usr/local/bin/hub:2048:in `create'
	from /usr/local/bin/hub:1586:in `run'
	from /usr/local/bin/hub:2514:in `initialize'
	from /usr/local/bin/hub:2518:in `new'
	from /usr/local/bin/hub:2518:in `execute'
	from /usr/local/bin/hub:2569:in `<main>' 
```

**Comment by mislav** [comment]
Hello, you're using a very old version of hub. Sorry for the late reply. Please uninstall that version and install the latest one. If you were using Homebrew to install it in the first place, you can do `brew upgrade hub`.
