### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by k-mats** [github/hub#1142]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
github.com/github/hub/github.(*Project).WebURL(0x0, 0x0, 0x0, 0x0, 0x0, 0xc208070720, 0x1b, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/github/project.go:30 +0x91f
github.com/github/hub/commands.compare(0x68ba20, 0xc2080641b0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/compare.go:78 +0x264
github.com/github/hub/commands.(*Command).Call(0x68ba20, 0xc2080641b0, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/commands.go:47 +0x184
github.com/github/hub/commands.(*Runner).Call(0xc20802b120, 0x68ba20, 0xc2080641b0, 0x0, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/runner.go:90 +0x54
github.com/github/hub/commands.(*Runner).Execute(0xc20802b120, 0x0, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/runner.go:82 +0x215
main.main()
	/private/tmp/hub20150413-43416-1y88pg5/hub-2.2.1/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

**Comment by k-mats** [comment]
git & hub versions when the runtime error occurred:
```
git version 2.6.4
hub version 2.2.1
```

I just upgraded hub version from 2.2.1 to 2.2.2 and it seems to have been fixed.
Sorry to send an unnecessary crash report.

**Comment by mislav** [comment]
No problem! Thanks for the update. I'm glad you solved it.
