### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jvican** [github/hub#1273]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x77e480, 0xc420014140)
	/usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/github/hub/github.(*Client).CreatePullRequest(0xc420049b60, 0xc4200113c0, 0xc4200d56e0, 0xc420049bc8, 0xc4201d8c90, 0x0)
	/tmp/go/src/github.com/github/hub/github/client.go:107 +0x1ed
github.com/github/hub/commands.pullRequest(0x99cd20, 0xc420088090)
	/tmp/go/src/github.com/github/hub/commands/pull_request.go:214 +0xd92
github.com/github/hub/commands.(*Command).Call(0x99cd20, 0xc420088090, 0x40b6b9, 0x7f3763)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc420015730, 0x99cd20, 0xc420088090, 0xc, 0xc420063cb0, 0x450310)
	/tmp/go/src/github.com/github/hub/commands/runner.go:93 +0x3f
github.com/github/hub/commands.(*Runner).Execute(0xc420015730, 0x811620, 0xc4200176b0, 0xc4200001a0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:85 +0x2cb
main.main()
	/build/hub/src/github-hub-7988c4b/main.go:12 +0x49

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.9.3
hub version 2.2.5
```

**Comment by mislav** [comment]
This crash got fixed in [v2.2.6](https://github.com/github/hub/releases/tag/v2.2.6). Please upgrade to the latest version of the 2.2.x series (currently 2.2.8), and report any problems you might have after the upgrade. Thank you!
