### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by david-caro** [github/hub#1283]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x8bea80, 0xc82000e170)
	/usr/lib/golang/src/runtime/panic.go:443 +0x4e9
github.com/github/hub/github.(*Client).CreatePullRequest(0xc82018d930, 0xc820116180, 0xc820342630, 0x0, 0x7f44ee177028, 0xc8203e8490)
	/builddir/build/BUILD/hub-7988c4b6b18b0fba0a1483e972cc45bad56e43ad/src/github.com/github/hub/github/client.go:107 +0x2b7
github.com/github/hub/commands.pullRequest(0xbde920, 0xc820018240)
	/builddir/build/BUILD/hub-7988c4b6b18b0fba0a1483e972cc45bad56e43ad/src/github.com/github/hub/commands/pull_request.go:214 +0x1c42
github.com/github/hub/commands.(*Command).Call(0xbde920, 0xc820018240, 0x0, 0x0)
	/builddir/build/BUILD/hub-7988c4b6b18b0fba0a1483e972cc45bad56e43ad/src/github.com/github/hub/commands/commands.go:47 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc82000f400, 0xbde920, 0xc820018240, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/hub-7988c4b6b18b0fba0a1483e972cc45bad56e43ad/src/github.com/github/hub/commands/runner.go:93 +0x5a
github.com/github/hub/commands.(*Runner).Execute(0xc82000f400, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/hub-7988c4b6b18b0fba0a1483e972cc45bad56e43ad/src/github.com/github/hub/commands/runner.go:85 +0x373
main.main()
	/builddir/build/BUILD/hub-7988c4b6b18b0fba0a1483e972cc45bad56e43ad/src/github.com/github/hub/main.go:12 +0x40

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.7.4
hub version 2.2.5
```

**Comment by mislav** [comment]
Thanks for reporting. This crash was fixed in [v2.2.6](https://github.com/github/hub/releases/tag/v2.2.6). Please upgrade to latest 2.2.x version.
