### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alileza** [github/hub#1315]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x37f120, 0xc42000e070)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:458 +0x243
github.com/github/hub/github.(*Client).CreatePullRequest(0xc420049b60, 0xc420071380, 0xc420368fc0, 0xc420049bf8, 0xc4203e0010, 0x0)
	/tmp/go/src/github.com/github/hub/github/client.go:107 +0x1ed
github.com/github/hub/commands.pullRequest(0x59fe40, 0xc4200a4120)
	/tmp/go/src/github.com/github/hub/commands/pull_request.go:214 +0xd92
github.com/github/hub/commands.(*Command).Call(0x59fe40, 0xc4200a4120, 0xc589, 0x3f42e6)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc420073770, 0x59fe40, 0xc4200a4120, 0xc, 0xc420079cb8, 0x503d0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:93 +0x3f
github.com/github/hub/commands.(*Runner).Execute(0xc420073770, 0x412060, 0xc420075590, 0xc420000340)
	/tmp/go/src/github.com/github/hub/commands/runner.go:85 +0x2c7
main.main()
	/private/tmp/hub-20161006-4113-akcr2x/hub-2.2.5/main.go:12 +0x49

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.9.2
hub version 2.2.5
```

**Comment by mislav** [comment]
Hi, this was fixed a long time ago; please upgrade hub to the latest version! `brew up && brew upgrade hub`
