### ISSUE TITLE
make test-all result in 11 errors from master

### ISSUE THREAD

**Issue by maxandersen** [github/hub#1320]
I want to try fix my old PR for tree checkouts but I still see `make test-all` constantly result in 12 errors. 

This is from a complete clean checkout and makes it hard to be sure I haven't broken anything.

Here is the output would be great if you could tell me if these failures are currently expected or not.

```
~/c/hub git:master ❯❯❯ make test-all                                                                                ⏎
script/test
ok  	github.com/github/hub/cmd	0.011s
--- FAIL: TestFlagToAddRemote (1.31s)
	assert.go:16: /tmp/max/go/src/github.com/github/hub/commands/init_test.go:47
	assert.go:25: ! "git --git-dir /tmp/max/go/src/github.com/github/hub/commands/.git remote add origin git@github.com:jingweno/commands.git" != "git --git-dir /tmp/max/go/src/github.com/github/hub/commands/.git remote add origin git@github.com:maxandersen/commands.git"
--- FAIL: TestInitInAnotherDir (1.30s)
	assert.go:16: /tmp/max/go/src/github.com/github/hub/commands/init_test.go:69
	assert.go:25: ! "git --git-dir /tmp/max/go/src/github.com/github/hub/commands/my project/.git remote add origin git@github.com:jingweno/my-project.git" != "git --git-dir /tmp/max/go/src/github.com/github/hub/commands/my project/.git remote add origin git@github.com:maxandersen/my-project.git"
--- FAIL: TestSeparateGitDir (1.35s)
	assert.go:16: /tmp/max/go/src/github.com/github/hub/commands/init_test.go:91
	assert.go:25: ! "git --git-dir /tmp/max/go/src/github.com/github/hub/commands/my/playground/.git remote add origin git@github.com:jingweno/playground.git" != "git --git-dir /tmp/max/go/src/github.com/github/hub/commands/my/playground/.git remote add origin git@github.com:maxandersen/playground.git"
--- FAIL: TestTransformRemoteArgs (0.94s)
	assert.go:16: /tmp/max/go/src/github.com/github/hub/commands/remote_test.go:32
	assert.go:37: !  Failure
FAIL
FAIL	github.com/github/hub/commands	5.535s
?   	github.com/github/hub/fixtures	[no test files]
ok  	github.com/github/hub/git	0.895s
ok  	github.com/github/hub/github	1.350s
ok  	github.com/github/hub/ui	0.011s
ok  	github.com/github/hub/utils	0.011s
?   	github.com/github/hub/version	[no test files]
tmux 2.3
	from /Users/max/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in  `<main>'
	from /Users/max/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in  `eval'
	from /Users/max/.rvm/gems/ruby-2.3.0/bin/bundle:23:in  `<main>'
	from /Users/max/.rvm/gems/ruby-2.3.0/bin/bundle:23:in  `load'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/exe/bundle:19:in  `<top (required)>'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in  `with_friendly_errors'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/exe/bundle:27:in  `block in <top (required)>'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in  `start'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in  `start'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in  `dispatch'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in  `invoke_command'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in  `run'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in  `exec'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in  `run'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in  `kernel_load'
	from /Users/max/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in  `load'
	from /Users/max/code/hub/vendor/bundle/ruby/2.3.0/bin/cucumber:23:in  `<top (required)>'
	from /Users/max/code/hub/vendor/bundle/ruby/2.3.0/bin/cucumber:23:in  `load'
	from /Users/max/code/hub/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.15/bin/cucumber:11:in  `<top (required)>'
	from /Users/max/code/hub/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.15/bin/cucumber:11:in  `require'
	from /Users/max/code/hub/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.15/lib/cucumber/cli/main.rb:8:in  `<top (required)>'
	from /Users/max/code/hub/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.15/lib/cucumber/cli/main.rb:8:in  `require'
	from /Users/max/code/hub/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.15/lib/cucumber.rb:8:in  `<top (required)>'
	from /Users/max/code/hub/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.15/lib/cucumber.rb:8:in  `require'
Using the all profile...
...............................................................................................................................F------....F---....F---..........................F---....F---....F------....F-----.....F---......F------.....F--.....F--................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

(::) failed steps (::)

Broken pipe (Errno::EPIPE)
./features/support/env.rb:126:in `/^I type "([^"]*)"$/'
features/authentication.feature:30:in `And I type "kitty"'

Broken pipe (Errno::EPIPE)
./features/support/env.rb:126:in `/^I type "([^"]*)"$/'
features/authentication.feature:68:in `And I type "kitty"'

Broken pipe (Errno::EPIPE)
./features/support/env.rb:126:in `/^I type "([^"]*)"$/'
features/authentication.feature:91:in `And I type "kitty"'

Broken pipe (Errno::EPIPE)
./features/support/env.rb:126:in `/^I type "([^"]*)"$/'
features/authentication.feature:167:in `And I type "WRONG"'

Broken pipe (Errno::EPIPE)
./features/support/env.rb:126:in `/^I type "([^"]*)"$/'
features/authentication.feature:187:in `And I type "PERSONALACCESSTOKEN"'

Broken pipe (Errno::EPIPE)
./features/support/env.rb:126:in `/^I type "([^"]*)"$/'
features/authentication.feature:219:in `And I type "kitty"'

Broken pipe (Errno::EPIPE)
./features/support/env.rb:126:in `/^I type "([^"]*)"$/'
features/authentication.feature:252:in `And I type "kitty"'

expected "github.com password for maxandersen (never stored): Error creating repository: Unauthorized (HTTP 401)\nBad credentials\n" to include "github.com password for mislav@example.com (never stored):"
Diff:
@@ -1,2 +1,3 @@
-github.com password for mislav@example.com (never stored):
+github.com password for maxandersen (never stored): Error creating repository: Unauthorized (HTTP 401)
+Bad credentials
 (RSpec::Expectations::ExpectationNotMetError)
features/authentication.feature:274:in `Then the output should contain "github.com password for mislav@example.com (never stored):"'

Broken pipe (Errno::EPIPE)
./features/support/env.rb:126:in `/^I type "([^"]*)"$/'
features/authentication.feature:300:in `And I type "kitty"'

expected "https://github.com/mislav/coral\n" to include "github.com username:"
Diff:
@@ -1,2 +1,2 @@
-github.com username:
+https://github.com/mislav/coral
 (RSpec::Expectations::ExpectationNotMetError)
features/authentication.feature:318:in `Then the output should contain "github.com username:"'

expected "https://github.com/mislav/coral\n" to include "github.com username:"
Diff:
@@ -1,2 +1,2 @@
-github.com username:
+https://github.com/mislav/coral
 (RSpec::Expectations::ExpectationNotMetError)
features/authentication.feature:332:in `Then the output should contain "github.com username:"'

Failing Scenarios:
cucumber -p all features/authentication.feature:5 # Scenario: Ask for username & password, create authorization
cucumber -p all features/authentication.feature:38 # Scenario: Rename & retry creating authorization if there's a token name collision
cucumber -p all features/authentication.feature:73 # Scenario: Avoid getting caught up in infinite recursion while retrying token names
cucumber -p all features/authentication.feature:158 # Scenario: Wrong password
cucumber -p all features/authentication.feature:177 # Scenario: Personal access token used instead of password
cucumber -p all features/authentication.feature:197 # Scenario: Two-factor authentication, create authorization
cucumber -p all features/authentication.feature:227 # Scenario: Retry entering two-factor authentication code
cucumber -p all features/authentication.feature:259 # Scenario: Special characters in username & password
cucumber -p all features/authentication.feature:279 # Scenario: Enterprise fork authentication with username & password, re-using existing authorization
cucumber -p all features/authentication.feature:308 # Scenario: Broken config is missing user.
cucumber -p all features/authentication.feature:322 # Scenario: Broken config is missing user and interactive input is empty.

334 scenarios (11 failed, 323 passed)
2085 steps (11 failed, 42 skipped, 2032 passed)
2m21.724s
make: *** [test-all] Error 1
```

**Comment by mislav** [comment]
Thanks for reporting! Now fixed.
