### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by deadlyicon** [github/hub#1331]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x382280, 0xc420010130)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/github/hub/git.WorkdirName(0xc420112420, 0x28, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/git/git.go:70 +0xb6
github.com/github/hub/commands.create(0x5a5740, 0xc4200acfa0)
	/tmp/go/src/github.com/github/hub/commands/create.go:66 +0x6a
github.com/github/hub/commands.(*Command).Call(0x5a5740, 0xc4200acfa0, 0x7fff5fbff55c, 0x6)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc42007f770, 0x5a5740, 0xc4200acfa0, 0x6, 0xc42010c090, 0xc420055ed8, 0x2079)
	/tmp/go/src/github.com/github/hub/commands/runner.go:108 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc42007f770, 0x415c30, 0x7d5ee, 0xc4201080c0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:96 +0x1e9
main.main()
	/private/tmp/hub-20160912-40594-1n8dwaa/hub-2.2.8/main.go:14 +0x51

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.10.0
hub version 2.2.8
```

**Comment by mislav** [comment]
Thanks for reporting! If you go to the same directory where you've experienced this crash, and do `git rev-parse --show-toplevel`, what do you get?

**Comment by deadlyicon** [comment]
sorry @mislav I've lost the ability to recreate this error. I wish I could help more. sorry

**Comment by mislav** [comment]
No worries. I'll keep this open and see if I can reproduce it somehow. Maybe it's caused by hub being run in a directory that doesn't exist anymore.

**Comment by deadlyicon** [comment]
I tried that and got this
```sh
$ git create
'create' must be run from inside a git repository
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
fatal: Unable to read current working directory: No such file or directory
```

**Comment by mislav** [comment]
Thanks for trying that. That looks like a different error message, and it didn't crash per se. I guess we're trying to find a condition when `git rev-parse --show-toplevel` is empty.

**Comment by mislav** [comment]
@sleexyz reports that this happens when `git create` is run after `git init --bare`. I can confirm that I can reproduce this! That's great, because before I didn't know where this comes from.
