### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by witmicko** [github/hub#1372]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x4ccc60, 0xc8200121e0)
	/home/travis/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:443 +0x4e9
github.com/github/hub/github.(*Client).CreatePullRequest(0xc8200f3930, 0xc82000f840, 0xc820119cb0, 0x0, 0x8ff028, 0xc820198380)
	/tmp/go/src/github.com/github/hub/github/client.go:122 +0x2b7
github.com/github/hub/commands.pullRequest(0x7f5280, 0xc82007efa0)
	/tmp/go/src/github.com/github/hub/commands/pull_request.go:238 +0x16e1
github.com/github/hub/commands.(*Command).Call(0x7f5280, 0xc82007efa0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/commands.go:45 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc820013790, 0x7f5280, 0xc82007efa0, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:94 +0x5a
github.com/github/hub/commands.(*Runner).Execute(0xc820013790, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:86 +0x3cf
main.main()
	/home/travis/gopath/src/github.com/github/hub/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.10.0
hub version 2.3.0-pre3
```

**Comment by mislav** [comment]
Thanks for reporting! This was fixed in later preleases. Just grab the latest one from the Releases section!
