### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Saketme** [github/hub#1386]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x4d2860, 0xc8200100c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/github/hub/github.(*Client).CreatePullRequest(0xc8200f3930, 0xc820013640, 0xc8203b5890, 0x0, 0xa40028, 0xc82042fcf0)
	/var/folders/w2/qdn1t69d2_j2prnthggt50_w0000gn/T/go/src/github.com/github/hub/github/client.go:122 +0x2b7
github.com/github/hub/commands.pullRequest(0x7fe4a0, 0xc82007d0e0)
	/var/folders/w2/qdn1t69d2_j2prnthggt50_w0000gn/T/go/src/github.com/github/hub/commands/pull_request.go:238 +0x16e1
github.com/github/hub/commands.(*Command).Call(0x7fe4a0, 0xc82007d0e0, 0x0, 0x0)
	/var/folders/w2/qdn1t69d2_j2prnthggt50_w0000gn/T/go/src/github.com/github/hub/commands/commands.go:45 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc820011640, 0x7fe4a0, 0xc82007d0e0, 0x0, 0x0, 0x0)
	/var/folders/w2/qdn1t69d2_j2prnthggt50_w0000gn/T/go/src/github.com/github/hub/commands/runner.go:94 +0x5a
github.com/github/hub/commands.(*Runner).Execute(0xc820011640, 0x0, 0x0, 0x0)
	/var/folders/w2/qdn1t69d2_j2prnthggt50_w0000gn/T/go/src/github.com/github/hub/commands/runner.go:86 +0x3cf
main.main()
	/private/tmp/hub-20160829-10922-hjxg9s/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.10.1 (Apple Git-78)
hub version 2.3.0-pre3
```

**Comment by mislav** [comment]
[This got fixed in 2.3.0-pre4](https://github.com/github/hub/releases/tag/v2.3.0-pre4). Please download the latest 2.3.0-prerelease!
