### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by j1z0** [github/hub#1418]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x4c3e60, 0xc820012160)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:443 +0x4e9
github.com/github/hub/github.(*Client).CreatePullRequest(0xc820181930, 0xc820014340, 0xc82038abd0, 0x0, 0xa80000, 0xc82042c220)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/github/client.go:107 +0x2b7
github.com/github/hub/commands.pullRequest(0x7e8880, 0xc8200a6090)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/pull_request.go:214 +0x1c42
github.com/github/hub/commands.(*Command).Call(0x7e8880, 0xc8200a6090, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/commands.go:47 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc820063460, 0x7e8880, 0xc8200a6090, 0x0, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/runner.go:93 +0x5a
github.com/github/hub/commands.(*Runner).Execute(0xc820063460, 0x0, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/runner.go:85 +0x367
main.main()
	/private/tmp/hub-20160812-78151-166w75l/hub-2.2.4/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.9.3
hub version 2.2.4
```

**Comment by mislav** [comment]
Thanks for reporting! This was already fixed. Please upgrade to latest hub v2.2.x and try again!
