### ISSUE TITLE
There is a flanky crashes when trying to create pull requests like this ``` hub pull-request -b staging ```

### ISSUE THREAD

**Issue by mpospelov** [github/hub#1429]
**Report:**
Crash report - runtime error: invalid memory address or nil pointer dereference

Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x4c4000, 0xc8200100f0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:443 +0x4e9
github.com/github/hub/github.(*Client).CreatePullRequest(0xc820173930, 0xc82000b9c0, 0xc8203541b0, 0x0, 0xa40028, 0xc82040a930)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/github/client.go:107 +0x2b7
github.com/github/hub/commands.pullRequest(0x7e8880, 0xc820090090)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/pull_request.go:214 +0x1c42
github.com/github/hub/commands.(*Command).Call(0x7e8880, 0xc820090090, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/commands.go:47 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc820011560, 0x7e8880, 0xc820090090, 0x0, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/runner.go:93 +0x5a
github.com/github/hub/commands.(*Runner).Execute(0xc820011560, 0x0, 0x0, 0x0)
	/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/go/src/github.com/github/hub/commands/runner.go:85 +0x367
main.main()
	/private/tmp/hub-20160814-33207-3ih85c/hub-2.2.5/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.10.0
hub version 2.2.5
```

**Comment by mislav** [comment]
Thanks for reporting! This was fixed in later versions of hub. Please upgrade!
