### ISSUE TITLE
hub pull-request panics with "fatal error: MSpanList_Insert"

### ISSUE THREAD

**Issue by technosophos** [github/hub#1457]
When trying to create a pull request with this commit: https://github.com/kubernetes/helm/pull/2338/commits/6246fa12a807e5c6ceb863f38dd6afa05ffc14fb

```console
⇒  hub pull-request
failed MSpanList_Insert 0x7678c8 0x2c6aaee514689 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x6a4228, 0x7678c8)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x6a0e20, 0x21, 0x10100000000, 0x8)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:240 +0x66

goroutine 42 [running]:
runtime.switchtoM()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:198 fp=0xc2080c11b0 sp=0xc2080c11a8
runtime.mallocgc(0x41f13, 0x32f8c0, 0x1, 0xc207ff63e7)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:199 +0x9f3 fp=0xc2080c1260 sp=0xc2080c11b0
runtime.newarray(0x32f8c0, 0x41f13, 0xc20802c7c0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:365 +0xc1 fp=0xc2080c1298 sp=0xc2080c1260
runtime.makeslice(0x321280, 0x41f13, 0x41f13, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/slice.go:32 +0x15c fp=0xc2080c12e0 sp=0xc2080c1298
runtime.gobytes(0x4000000, 0x41f13, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/string.go:248 +0x9f fp=0xc2080c1330 sp=0xc2080c12e0
crypto/x509._Cfunc_GoBytes(0x4000000, 0x41f13, 0x0, 0x0, 0x0)
	crypto/x509/_obj/_cgo_gotypes.go:62 +0x54 fp=0xc2080c1360 sp=0xc2080c1330
crypto/x509.initSystemRoots()
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/x509/root_cgo_darwin.go:76 +0x17d fp=0xc2080c13d8 sp=0xc2080c1360
sync.(*Once).Do(0x699278, 0x536470)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/once.go:44 +0xd4 fp=0xc2080c13f0 sp=0xc2080c13d8
crypto/x509.systemRootsPool(0x72)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/x509/root.go:15 +0x36 fp=0xc2080c1408 sp=0xc2080c13f0
crypto/x509.(*Certificate).Verify(0xc20807e480, 0xc2080a8480, 0xe, 0xc20809c120, 0x0, 0xed094697f, 0x159bc021, 0x690920, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/x509/verify.go:219 +0x88 fp=0xc2080c1538 sp=0xc2080c1408
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc208030360, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/handshake_client.go:262 +0x6d6 fp=0xc2080c1ad0 sp=0xc2080c1538
crypto/tls.(*Conn).clientHandshake(0xc20806e000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/handshake_client.go:197 +0x1981 fp=0xc2080c1f50 sp=0xc2080c1ad0
crypto/tls.(*Conn).Handshake(0xc20806e000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:977 +0xf1 fp=0xc2080c1f90 sp=0xc2080c1f50
net/http.func·022()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:637 +0x3c fp=0xc2080c1fe0 sp=0xc2080c1f90
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080c1fe8 sp=0xc2080c1fe0
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:642 +0x88c

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc208030000, 0xc20801e340, 0x0, 0xc20802c140, 0x5, 0xc2080a8480, 0x12, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc208030000, 0xc20801e340, 0x2b6f8f, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:228 +0x4d4
github.com/github/hub/github.(*verboseTransport).RoundTrip(0xc20803b0b0, 0xc20801e340, 0xc20802c180, 0x0, 0x0)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/github/http.go:45 +0x223
net/http.send(0xc20801e340, 0x775948, 0xc20803b0b0, 0x32, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc20803b0e0, 0xc20801e340, 0x32, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc20803b0e0, 0xc20801e340, 0x536930, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc20803b0e0, 0xc20801e340, 0x4, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:177 +0x192
github.com/github/hub/Godeps/_workspace/src/github.com/jingweno/go-sawyer.(*Request).Do(0xc2080a82c0, 0x4610c0, 0x4, 0x0)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/jingweno/go-sawyer/request.go:36 +0xdb
github.com/github/hub/Godeps/_workspace/src/github.com/jingweno/go-sawyer.(*Request).Post(0xc2080a82c0, 0x407260)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/jingweno/go-sawyer/request.go:62 +0x3b
github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit.(*Request).Post(0xc2080a4150, 0x407260, 0xc20802c080, 0x309580, 0xc208042038, 0xc2080a4150, 0x0, 0x0)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit/request.go:34 +0x5f
github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit.func·004(0xc2080a4150, 0xc2080a8220, 0x0, 0x0)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit/client.go:68 +0x5d
github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit.sendRequest(0xc20803b350, 0xc2080a0070, 0xc2080878c0, 0x8)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit/client.go:137 +0xa7
github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit.(*Client).post(0xc20803b350, 0xc2080a0070, 0x407260, 0xc20802c080, 0x309580, 0xc208042038, 0x40)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit/client.go:69 +0x5b
github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit.(*PullRequestsService).Create(0xc2080a4110, 0x407260, 0xc20802c080, 0x0, 0x0)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/octokit/go-octokit/octokit/pull_requests.go:32 +0x89
github.com/github/hub/github.(*Client).CreatePullRequest(0xc2080423c8, 0xc208032600, 0xc2080a5690, 0x6, 0xc20809cf90, 0x26, 0xc20802da40, 0x35, 0xc20809a181, 0xb5, ...)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/github/client.go:106 +0x3ea
github.com/github/hub/commands.pullRequest(0x68d200, 0xc208058090)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/commands/pull_request.go:205 +0x1a15
github.com/github/hub/commands.(*Command).Call(0x68d200, 0xc208058090, 0x0, 0x0)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/commands/commands.go:47 +0x184
github.com/github/hub/commands.(*Runner).Call(0xc208028880, 0x68d200, 0xc208058090, 0x0, 0x0, 0x0)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/commands/runner.go:90 +0x54
github.com/github/hub/commands.(*Runner).Execute(0xc208028880, 0x0, 0x0, 0x0)
	/var/folders/p5/5940dcgj6jx_w1w_2c9nrfkr0000gn/T/go/src/github.com/github/hub/commands/runner.go:82 +0x215
main.main()
	/private/tmp/hub20150601-28583-7569md/main.go:12 +0x40

goroutine 39 [chan receive]:
net/http.(*Transport).dialConn(0xc208030000, 0x0, 0xc20802c140, 0x5, 0xc2080a8480, 0x12, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:643 +0x8d3
net/http.func·019()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:522 +0x335

goroutine 49 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1
```

(My local go is 1.8.0, not 1.4.2)

Here's the version:

```console
⇒  hub version
git version 2.11.0 (Apple Git-81)
hub version 2.2.1-g1e8f4f4
```
Hub installed from `brew`

**Comment by mislav** [comment]
Thanks for reporting this. This is the first time I'm seeing such an error.

Does this happen every time on `hub pull-request`? Have you tried updating to a newer Go 1.8.x version and building the project with that?

**Comment by technosophos** [comment]
I've actually entirely switched computers now (work laptop changed) and haven't reproduced this problem since. So it's probably safe to close. I'll re-open if I can recreate it.

**Comment by gr2m** [comment]
I see that error each time I try to run `hub` after upgrading to latest MacOS High Sierra
