### ISSUE TITLE
`make test-all` fails on HEAD of master

### ISSUE THREAD

**Issue by eljobe** [github/hub#1467]
Currently, when I do the following:
```
$> git clone github/hub
$> cd hub
$> make test-all
```

I get this output:
```
script/bootstrap
go version go1.6.3 darwin/amd64
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Installing ffi 1.9.3 with native extensions
Installing builder 3.2.2
Installing diff-lcs 1.2.5
Installing multi_json 1.10.1
Installing multi_test 0.1.1
Installing rspec-support 3.0.2
Installing hpricot 0.8.4 with native extensions
Installing mustache 0.99.4
Installing rack 1.4.1
Installing rdiscount 1.6.8 with native extensions
Installing tilt 1.3.3
Using bundler 1.13.0
Installing childprocess 0.5.3
Installing gherkin 2.12.2 with native extensions
Installing rspec-expectations 3.0.2
Installing rack-protection 1.2.0
Installing ronn 0.7.3
Installing cucumber 1.3.15
Installing sinatra 1.3.2
Installing aruba 0.5.4
Bundle complete! 4 Gemfile dependencies, 20 gems now installed.
Bundled gems are installed into ./vendor/bundle.
Everything OK.
script/test
# github.com/github/hub/github
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xf0eb]

runtime stack:
runtime.throw(0x4971c0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x982540)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x982540, 0x1, 0x4, 0xe367c0)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82006de58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x982540, 0x1, 0x10000000004, 0xed8f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x9839d0, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x9839d0, 0xe367c0)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0xaf60d0, 0x4, 0xe367c0)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820020a00)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc821d74918 sp=0xc821d74910
runtime.mallocgc(0x30, 0x41e1e0, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc821d749f0 sp=0xc821d74918
runtime.newobject(0x41e1e0, 0x13a868)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc821d74a18 sp=0xc821d749f0
cmd/compile/internal/gc.(*EscState).nodeEscState(0xc821ef94a0, 0xc820f46750, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:318 +0x192 fp=0xc821d74ae0 sp=0xc821d74a18
cmd/compile/internal/gc.(*EscState).track(0xc821ef94a0, 0xc820f46750)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:330 +0x72 fp=0xc821d74b10 sp=0xc821d74ae0
cmd/compile/internal/gc.esc(0xc821ef94a0, 0xc820f46750, 0xc820f46900)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:884 +0xa84 fp=0xc821d74d08 sp=0xc821d74b10
cmd/compile/internal/gc.esclist(0xc821ef94a0, 0xc820f269e0, 0xc820f46900)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:571 +0x44 fp=0xc821d74d28 sp=0xc821d74d08
cmd/compile/internal/gc.esc(0xc821ef94a0, 0xc820f46900, 0xc820f61320)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:619 +0x382 fp=0xc821d74f20 sp=0xc821d74d28
cmd/compile/internal/gc.esclist(0xc821ef94a0, 0xc820f26a20, 0xc820f61320)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:571 +0x44 fp=0xc821d74f40 sp=0xc821d74f20
cmd/compile/internal/gc.escfunc(0xc821ef94a0, 0xc820f61320)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:513 +0x20f fp=0xc821d74fc8 sp=0xc821d74f40
cmd/compile/internal/gc.escAnalyze(0xc8204a88f0, 0x2, 0x2, 0xc821d75100)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:436 +0x1ed fp=0xc821d75120 sp=0xc821d74fc8
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc821d75a70, 0xc820f61320, 0xc80000004c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:107 +0x281 fp=0xc821d751c8 sp=0xc821d75120
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820f759e0, 0xc80000004c, 0xc80000004c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:138 +0x1ca fp=0xc821d751f0 sp=0xc821d751c8
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820f76c40, 0x4c, 0xc80000004c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75218 sp=0xc821d751f0
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820f75b00, 0x4c, 0x4c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:130 +0x112 fp=0xc821d75240 sp=0xc821d75218
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820f76d40, 0x4c, 0xc80000004c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75268 sp=0xc821d75240
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820f6c1b0, 0xc80000004c, 0x4c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:125 +0x4b fp=0xc821d75290 sp=0xc821d75268
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820f76ea0, 0xc80000004c, 0xc80000004c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d752b8 sp=0xc821d75290
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820f75680, 0x4c, 0x9f0f31530000004c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:129 +0xea fp=0xc821d752e0 sp=0xc821d752b8
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820f76fa0, 0xc80000004c, 0xc821d75354)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75308 sp=0xc821d752e0
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc821d75a70, 0xc820f74a20, 0xc80000004a)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:81 +0x131 fp=0xc821d753b0 sp=0xc821d75308
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820f903f0, 0xc80000004a, 0xc80000004a)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:138 +0x1ca fp=0xc821d753d8 sp=0xc821d753b0
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820f90510, 0x4a, 0x15eef3430000004a)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:127 +0x9a fp=0xc821d75400 sp=0xc821d753d8
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820fd9880, 0xc80000004a, 0xc821d75474)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75428 sp=0xc821d75400
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc821d75a70, 0xc820f993b0, 0xc80000003e)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:81 +0x131 fp=0xc821d754d0 sp=0xc821d75428
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820faf710, 0x3e, 0x3e)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:138 +0x1ca fp=0xc821d754f8 sp=0xc821d754d0
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820faf7a0, 0x3e, 0xbd7b22050000003e)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:127 +0x9a fp=0xc821d75520 sp=0xc821d754f8
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820fd8ea0, 0xc80000003e, 0xc80000003e)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75548 sp=0xc821d75520
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820faecf0, 0x3e, 0xd7d9474b0000003e)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:129 +0xea fp=0xc821d75570 sp=0xc821d75548
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820fd8fa0, 0xc80000003e, 0xc821d755e4)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75598 sp=0xc821d75570
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc821d75a70, 0xc820fd2480, 0x3c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:81 +0x131 fp=0xc821d75640 sp=0xc821d75598
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820885200, 0x3c, 0x3c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:138 +0x1ca fp=0xc821d75668 sp=0xc821d75640
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc8208e0560, 0xc80000003c, 0x3c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75690 sp=0xc821d75668
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc8208853b0, 0xc80000003c, 0x3c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:130 +0x112 fp=0xc821d756b8 sp=0xc821d75690
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc8208e0640, 0xc80000003c, 0xc80000003c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d756e0 sp=0xc821d756b8
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820884480, 0x3c, 0x24c6fbb875e94712)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:129 +0xea fp=0xc821d75708 sp=0xc821d756e0
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc8208e0780, 0xc80000003c, 0xc821d7577c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75730 sp=0xc821d75708
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc821d75a70, 0xc82088b5f0, 0x3a)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:81 +0x131 fp=0xc821d757d8 sp=0xc821d75730
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820858120, 0xc80000003a, 0xc80000003a)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:138 +0x1ca fp=0xc821d75800 sp=0xc821d757d8
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820858240, 0x3a, 0x2fcc767fb5cf2eb)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:127 +0x9a fp=0xc821d75828 sp=0xc821d75800
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc8208e0de0, 0xc80000003a, 0xc821d7589c)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75850 sp=0xc821d75828
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc821d75a70, 0xc82085f7a0, 0x38)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:81 +0x131 fp=0xc821d758f8 sp=0xc821d75850
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820a2bb00, 0x38, 0x38)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:138 +0x1ca fp=0xc821d75920 sp=0xc821d758f8
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820a2c100, 0xc800000038, 0xc800000038)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75948 sp=0xc821d75920
cmd/compile/internal/gc.(*bottomUpVisitor).visitcode(0xc821d75a70, 0xc820a2bb90, 0x38, 0xaf5058629a9bf475)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:130 +0x112 fp=0xc821d75970 sp=0xc821d75948
cmd/compile/internal/gc.(*bottomUpVisitor).visitcodelist(0xc821d75a70, 0xc820a2c160, 0xc800000038, 0xc821d759e4)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:115 +0x46 fp=0xc821d75998 sp=0xc821d75970
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc821d75a70, 0xc820a2b680, 0xc800000036)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:81 +0x131 fp=0xc821d75a40 sp=0xc821d75998
cmd/compile/internal/gc.visitBottomUp(0xc820420ec0, 0x4c4730)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:63 +0xba fp=0xc821d75aa8 sp=0xc821d75a40
cmd/compile/internal/gc.escapes(0xc820420ec0)
	/usr/local/go/src/cmd/compile/internal/gc/esc.go:187 +0x2d fp=0xc821d75ac0 sp=0xc821d75aa8
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:455 +0x2073 fp=0xc821d75de0 sp=0xc821d75ac0
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc821d75e48 sp=0xc821d75de0
main.main()
	/usr/local/go/src/cmd/compile/main.go:32 +0x395 fp=0xc821d75f20 sp=0xc821d75e48
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc821d75f70 sp=0xc821d75f20
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc821d75f78 sp=0xc821d75f70
make: *** [test-all] Error 2
```

Any ideas?

**Comment by eljobe** [comment]
Upgraded Go to 1.8.1 and it no longer causes this trace.
