### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by IamCarbonMan** [github/hub#1510]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x781d20, 0xc42000e130)
	/usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/github/hub/git.WorkdirName(0xc4200ea400, 0x14, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/git/git.go:70 +0xb6
github.com/github/hub/commands.create(0x9a2620, 0xc420076fa0)
	/tmp/go/src/github.com/github/hub/commands/create.go:66 +0x6a
github.com/github/hub/commands.(*Command).Call(0x9a2620, 0xc420076fa0, 0x7ffcd0483cbf, 0x6)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc42000f6f0, 0x9a2620, 0xc420076fa0, 0x6, 0xc42005ff00, 0xc420043ed8, 0x401039)
	/tmp/go/src/github.com/github/hub/commands/runner.go:108 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc42000f6f0, 0x815910, 0x47dabe, 0xc4200e00c0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:96 +0x1e9
main.main()
	/build/hub/src/github-hub-80948b0/main.go:14 +0x51

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.13.1
hub version 2.2.9
```

**Comment by mislav** [comment]
Thanks for reporting! This happens when you try to run hub commands within a bare git repo. This was fixed in 01c3099abe56a8dcca41e285c11c0f6f860cc338 and will be part of next release.
