### ISSUE TITLE
panic with index out of range, v2.3.0-pre10

### ISSUE THREAD

**Issue by dkinzer** [github/hub#1588]
I'm getting the following panic error when trying to create an new repository (and I'm not within a bare git repo):

## Error:
```
(projects)  > ~/Downloads/hub-darwin-amd64-2.3.0-pre10/bin/hub clone tullibraries/tul_omeka_playbook
runtime error: index out of range

goroutine 1 [running]:
panic(0x13a6040, 0x15defb0)
        /home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/github/hub/github.(*yamlConfigDecoder).Decode(0x16060f0, 0x15b76e0, 0xc42000c080, 0xc4200d5100, 0x0, 0x1)
        /tmp/go/src/github.com/github/hub/github/config_decoder.go:40 +0x404
github.com/github/hub/github.(*configService).Load(0xc4200fbb40, 0xc4200d4b00, 0x1a, 0xc4200d5100, 0x0, 0x0)
        /tmp/go/src/github.com/github/hub/github/config_service.go:42 +0xc0
github.com/github/hub/github.CurrentConfig(0x7fff5fbff719)
        /tmp/go/src/github.com/github/hub/github/config.go:261 +0x130
github.com/github/hub/github.newProject(0x7fff5fbff70c, 0xc, 0x7fff5fbff719, 0x12, 0x140c146, 0xa, 0x0, 0x0, 0x2)
        /tmp/go/src/github.com/github/hub/github/project.go:164 +0x351
github.com/github/hub/github.NewProject(0x7fff5fbff70c, 0xc, 0x7fff5fbff719, 0x12, 0x0, 0x0, 0x200)
        /tmp/go/src/github.com/github/hub/github/project.go:135 +0x72
github.com/github/hub/commands.transformCloneArgs(0xc4200b04d0)
        /tmp/go/src/github.com/github/hub/commands/clone.go:84 +0x2b4
github.com/github/hub/commands.clone(0x15e4e20, 0xc4200b04d0)
        /tmp/go/src/github.com/github/hub/commands/clone.go:44 +0x3e
github.com/github/hub/commands.(*Command).Call(0x15e4e20, 0xc4200b04d0, 0x7fff5fbff706, 0x5)
        /tmp/go/src/github.com/github/hub/commands/commands.go:45 +0x140
github.com/github/hub/commands.(*Runner).Call(0xc420013810, 0x15e4e20, 0xc4200b04d0, 0x5, 0xc420011ab0, 0xc4200fbe78, 0xc42000f650)
        /tmp/go/src/github.com/github/hub/commands/runner.go:109 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc420013810, 0x1423788, 0x0, 0x0, 0xc)
        /tmp/go/src/github.com/github/hub/commands/runner.go:94 +0x376
main.main()
        /home/travis/gopath/src/github.com/github/hub/main.go:16 +0x51
```

I'm also seeing the error if I try to run a pull-request from a non bare repo.

## Version Info:
```
git version 2.14.2
hub version 2.3.0-pre10
```

**Comment by patheticpat** [comment]
This looks like your hub config file (`~/.config/hub` by default) got corrupted somehow.

**Comment by dkinzer** [comment]
@pakwit thank you!  I looked at the file and it was composed of merely one line...
```
github.com:
```

After deleting the file and re-cloning the new config file looks correct.

**Comment by patheticpat** [comment]
Do you have any idea what happened to your `~/.config/hub`?

Anyway, hub should probably ignore the invalid entry instead of panicking.

**Comment by dkinzer** [comment]
I suspect that what happened  with `~/.config/hub` is that I failed to properly authenticate at setup.  I'm working on a new computer and I was installing hub anew.

Well, I don't know if that's the real cause.  I had to authenticate a couple of times in a row because I have 2FA turned on and I failed to enter the code fast enough the first time.

But again, that's just a guess.

**Comment by mislav** [comment]
Thank you for the report @dkinzer. Ideally, hub shouldn't crash if the config file is missing some lines. We'll try to handle that better in future versions.
