### ISSUE TITLE
CGI is a Class in Ruby 2.5 not a module

### ISSUE THREAD

**Issue by schneems** [github/hub#1662]
If you try to require `erb` after requiring `hub` on Ruby 2.5 it will blow up:

```
require 'hub'
require 'erb'
Traceback (most recent call last):
        8: from /Users/rschneeman/.rubies/ruby-2.5.0/bin/irb:11:in `<main>'
        7: from (irb):2
        6: from /Users/rschneeman/.rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        5: from /Users/rschneeman/.rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        4: from /Users/rschneeman/.rubies/ruby-2.5.0/lib/ruby/2.5.0/erb.rb:15:in `<top (required)>'
        3: from /Users/rschneeman/.rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from /Users/rschneeman/.rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        1: from /Users/rschneeman/.rubies/ruby-2.5.0/lib/ruby/2.5.0/cgi/util.rb:2:in `<top (required)>'
TypeError (CGI is not a class)
```

Looks like it's due to the `speedy_stlib` 

```ruby
unless defined?(CGI)
  prevent_require.call 'cgi'

  module CGI
    ESCAPE_RE = /[^a-zA-Z0-9 .~_-]/

    def self.escape(s)
      s.to_s.gsub(ESCAPE_RE) {|match|
        '%' + match.unpack('H2' * match.bytesize).join('%').upcase
      }.tr(' ', '+')
    end

    def self.unescape(s)
      s.tr('+', ' ').gsub(/((?:%[0-9a-fA-F]{2})+)/) {
        [$1.delete('%')].pack('H*')
      }
    end
  end
end
```

**Comment by mislav** [comment]
hub hasn't been implemented in Ruby [since 2014](https://github.com/github/hub/releases/tag/v2.2.0-preview1). Please download the most recent release from the Releases section.

**Comment by schneems** [comment]
That explains why I couldn’t find that file in the repo. Thanks.
