### ISSUE TITLE
git hub issue: WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by speedplane** [github/hub#1689]
I'm running the command `git hub issue` on the command line, and I get the following error with stack trace:

```
> git hub issue
GitHub password:
An OAuth token for this host already exists. Shall I delete it? [y/N] y
A GitHub authentication token is now stored in git's credential helper
To revoke access, visit https://github.com/settings/applications
Traceback (most recent call last):
  File "C:\Python27\Scripts\git-hub-script.py", line 11, in <module>
    load_entry_point('git-spindle==3.4.2', 'console_scripts', 'git-hub')()
  File "c:\python27\lib\site-packages\gitspindle\__init__.py", line 661, in hub
    GitHub().main()
  File "c:\python27\lib\site-packages\gitspindle\__init__.py", line 473, in main
    func(opts)
  File "c:\python27\lib\site-packages\gitspindle\github.py", line 789, in issue
    title, body = self.edit_msg(None, body, extra, 'ISSUE_EDITMSG' + ext)
  File "c:\python27\lib\site-packages\gitspindle\__init__.py", line 346, in edit_msg
    self.shell[editor[0]](*editor[1:], redirect=False)
  File "c:\python27\lib\site-packages\whelk\__init__.py", line 178, in __call__
    sp = Popen([str(self.name)] + [str(x) for x in self.args], **(self.sp_kwargs))
  File "c:\python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

I tried on both windows command line and cygwin, same result.

Version info:
Windows 10
```
$ git --version
git version 2.9.0.windows.1
```

**Comment by mislav** [comment]
This project is not invoked as `git hub` (instead, it's only invoked as `hub`) and is not a Python script (we are written in Go). I think you are opening an issue in the wrong project! 😉
