### ISSUE TITLE
Pushing to remote fails

### ISSUE THREAD

**Issue by wagnerand** [github/hub#1722]
`hub` just started failing to push, when `git` works fine:

```
$ git push
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 1.23 KiB | 315.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:23:in `ip': getaddrinfo: Name or service not known (SocketError)
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:23:in `initialize'
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:106:in `new'
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:106:in `add_shard'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:33:in `block in create_statsd'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:33:in `each'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:33:in `create_statsd'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:20:in `stats'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:244:in `<module:GitHub>'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:12:in `<top (required)>'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/lib/github/logger.rb:3:in `<top (required)>'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/lib/github.rb:137:in `<module:GitHub>'
remote: 	from /data/github/releases/deploy-b/lib/github.rb:20:in `<top (required)>'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:230:in `<top (required)>'
remote: 	from /data/github/releases/deploy-b/vendor/ruby/44c51a28900fc53699489c87289294b79ee365d3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
remote: 	from /data/github/releases/deploy-b/vendor/ruby/44c51a28900fc53699489c87289294b79ee365d3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
To github.com:wagnerand/addons-server.git
 ! [remote rejected]       ts -> ts (pre-receive hook declined)
```

```
$ \git push
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 1.23 KiB | 252.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:.../....git
   675facd32d..96d3623e01  ts -> ts
```

```
$ git --version
git version 2.17.0
hub version 2.2.9
```

on macOS 10.13.4

**Comment by mislav** [comment]
Thanks for reporting. This looks like a network error on a remote, and not a bug with hub. It might have been a coincidence that retrying with `git` worked.
