### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by mantzas** [github/hub#1729]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x6f8c60, 0x905950)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/github/hub/github.(*Client).FetchRelease(0xc42000e100, 0xc420010800, 0x7ffc1cabd125, 0x6, 0xc420069cd8, 0x411649, 0xc42005add0)
	/home/mantzas/go/src/github.com/github/hub/github/client.go:317 +0x1c1
github.com/github/hub/commands.showRelease(0x90c920, 0xc4200e04d0)
	/home/mantzas/go/src/github.com/github/hub/commands/release.go:220 +0x1af
github.com/github/hub/commands.(*Command).Call(0x90c860, 0xc4200e04d0, 0x7, 0xc420095101)
	/home/mantzas/go/src/github.com/github/hub/commands/commands.go:45 +0x124
github.com/github/hub/commands.(*Runner).Call(0xc42005ac30, 0x90c860, 0xc4200e04d0, 0x7, 0xc4200bf228, 0x6a9da0, 0x4534f0)
	/home/mantzas/go/src/github.com/github/hub/commands/runner.go:109 +0x3c
github.com/github/hub/commands.(*Runner).Execute(0xc42005ac30, 0x76f058, 0xc420069f78, 0x40594c, 0xc4200220b8)
	/home/mantzas/go/src/github.com/github/hub/commands/runner.go:94 +0x35c
main.main()
	/home/mantzas/go/src/github.com/github/hub/main.go:16 +0x51

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.17.0
hub version 2.3.0-pre10
```

**Comment by mislav** [comment]
Fixed in afdcb6120bbe80b2483961adbd7efaa2e7a12fba
