### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by s-fujimoto** [github/hub#1738]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x12f89c0, 0x15098a0)
	/usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/github/hub/github.(*Branch).ShortName(0x0, 0xc4200a11b8, 0x6)
	/var/folders/vp/2b51_dy91r3b5bbjsv1lbj4c0000gq/T/go/src/github.com/github/hub/github/branch.go:18 +0x40
github.com/github/hub/commands.showPr(0x1510320, 0xc4200e64d0)
	/var/folders/vp/2b51_dy91r3b5bbjsv1lbj4c0000gq/T/go/src/github.com/github/hub/commands/pr.go:248 +0x829
github.com/github/hub/commands.(*Command).Call(0x15100e0, 0xc4200e64d0, 0x2, 0xc42009b101)
	/var/folders/vp/2b51_dy91r3b5bbjsv1lbj4c0000gq/T/go/src/github.com/github/hub/commands/commands.go:45 +0x124
github.com/github/hub/commands.(*Runner).Call(0xc420096cc0, 0x15100e0, 0xc4200e64d0, 0x2, 0xc4200a72f8, 0x12aa940, 0x1052550)
	/var/folders/vp/2b51_dy91r3b5bbjsv1lbj4c0000gq/T/go/src/github.com/github/hub/commands/runner.go:109 +0x3c
github.com/github/hub/commands.(*Runner).Execute(0xc420096cc0, 0x136edb0, 0xc420057f78, 0x1005c9c, 0xc42008c058)
	/var/folders/vp/2b51_dy91r3b5bbjsv1lbj4c0000gq/T/go/src/github.com/github/hub/commands/runner.go:94 +0x35c
main.main()
	/Users/fujimoto.shinji/.ghq/github.com/github/hub/main.go:16 +0x51

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.14.1
hub version 2.3.0-pre10-136-g1e5bb95
```

**Comment by s-fujimoto** [comment]
Sorry, misstake
