### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by jcvenegas** [github/hub#1744]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x704740, 0x90a0c0)
	/usr/lib/golang/src/runtime/panic.go:491 +0x283
github.com/github/hub/github.(*Client).FetchRelease(0xc420162000, 0xc420160040, 0x7fff5820030e, 0x5, 0x10, 0x6ede40, 0xdb725c17)
	/tmp/go/src/github.com/github/hub/github/client.go:317 +0x1d8
github.com/github/hub/commands.showRelease(0x910dc0, 0xc4200b8630)
	/tmp/go/src/github.com/github/hub/commands/release.go:220 +0x1af
github.com/github/hub/commands.(*Command).Call(0x910d00, 0xc4200b8630, 0x76f78f, 0x7fff58200301)
	/tmp/go/src/github.com/github/hub/commands/commands.go:45 +0x136
github.com/github/hub/commands.(*Runner).Call(0xc420046c10, 0x910d00, 0xc4200b8630, 0x7, 0xc420013d80, 0xc420055e68, 0x7028a0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:109 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc420046c10, 0x777150, 0x405e64, 0xc42007a058, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:94 +0x369
main.main()
	/home/user/go/src/github.com/github/hub/main.go:16 +0x51

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.14.3
hub version 2.3.0-pre10-136-g1e5bb95
```

**Comment by mislav** [comment]
Thank you for reporting! Fixed in afdcb6120bbe80b2483961adbd7efaa2e7a12fba
