### ISSUE TITLE
Crash in `cherry-pick`

### ISSUE THREAD

**Issue by simbo1905** [github/hub#1773]
I was trying `hub cherry-pick https://github.com/sobolevn/git-secret/pull/185/commits/459452f8dbf5a917dc7e9ca3c3be0c5625f198b7` which is a bit of a strange commit which I created by editing the page on someone else repo which made a PR with just that change on it so not part of a fork or branch. That seemed to crash hub.

Crash report - runtime error: invalid memory address or nil pointer dereference

Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x12fab60, 0x150b8a0)
	/usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:502 +0x229
github.com/github/hub/commands.parseCherryPickProjectAndSha(0x7fff5fbffa78, 0x60, 0x60, 0x1011969, 0xc420059d78, 0x1011969)
	/tmp/go/src/github.com/github/hub/commands/cherry_pick.go:86 +0x65b
github.com/github/hub/commands.transformCherryPickArgs(0xc4200c04d0)
	/tmp/go/src/github.com/github/hub/commands/cherry_pick.go:42 +0x6f
github.com/github/hub/commands.cherryPick(0x1511720, 0xc4200c04d0)
	/tmp/go/src/github.com/github/hub/commands/cherry_pick.go:32 +0x95
github.com/github/hub/commands.(*Command).Call(0x1511720, 0xc4200c04d0, 0xb, 0xc420011101)
	/tmp/go/src/github.com/github/hub/commands/commands.go:45 +0x124
github.com/github/hub/commands.(*Runner).Call(0xc42004ace0, 0x1511720, 0xc4200c04d0, 0xb, 0xc420092798, 0x12aca80, 0x1052550)
	/tmp/go/src/github.com/github/hub/commands/runner.go:109 +0x3c
github.com/github/hub/commands.(*Runner).Execute(0xc42004ace0, 0x1371970, 0xc420059f78, 0x1005c9c, 0xc420080058)
	/tmp/go/src/github.com/github/hub/commands/runner.go:94 +0x35c
main.main()
	/private/tmp/hub-20180607-56632-k90ovw/hub-2.4.0/main.go:16 +0x51

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.14.3 (Apple Git-98)
hub version 2.4.0
```

**Comment by mislav** [comment]
Thank you for reporting!
