### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by rnvandemark** [github/hub#2068]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x8ca4a0, 0xc82000e0e0)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/github/hub/git.WorkdirName(0x0, 0x0, 0x0, 0x0)
	/build/hub-F8SKBG/hub-2.2.9/obj-x86_64-linux-gnu/src/github.com/github/hub/git/git.go:70 +0xf7
github.com/github/hub/commands.create(0xbf0320, 0xc820018f00)
	/build/hub-F8SKBG/hub-2.2.9/obj-x86_64-linux-gnu/src/github.com/github/hub/commands/create.go:66 +0xd6
github.com/github/hub/commands.(*Command).Call(0xbf0320, 0xc820018f00, 0x0, 0x0)
	/build/hub-F8SKBG/hub-2.2.9/obj-x86_64-linux-gnu/src/github.com/github/hub/commands/commands.go:47 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc82000f590, 0xbf0320, 0xc820018f00, 0x0, 0x0, 0x0, 0x0)
	/build/hub-F8SKBG/hub-2.2.9/obj-x86_64-linux-gnu/src/github.com/github/hub/commands/runner.go:108 +0x5e
github.com/github/hub/commands.(*Runner).Execute(0xc82000f590, 0x0, 0x0, 0x0, 0x0)
	/build/hub-F8SKBG/hub-2.2.9/obj-x86_64-linux-gnu/src/github.com/github/hub/commands/runner.go:96 +0x1df
main.main()
	/build/hub-F8SKBG/hub-2.2.9/obj-x86_64-linux-gnu/src/github.com/github/hub/main.go:14 +0x50

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.7.4
hub version 2.2.9
```

**Comment by mislav** [comment]
Hi thank you for reporting! This was fixed in 01c3099abe56a8dcca41e285c11c0f6f860cc338; please upgrade your hub to the latest version.
