### ISSUE TITLE
hub pull-request fails with error and panic

### ISSUE THREAD

**Issue by swechsler** [github/hub#2083]
```
$ hub --version
git version 1.8.3.1
hub version 2.7.1
$ hub pull-request -h <my branch>
interface conversion: interface {} is yaml.MapSlice, not []interface {}

goroutine 1 [running]:
panic(0x7202e0, 0xc00013a330)
        /usr/lib/golang/src/runtime/panic.go:513 +0x1b9
github.com/github/hub/github.(*yamlConfigDecoder).Decode(0xa16b80, 0x7d8000, 0xc00000e110, 0xc00000cae0, 0x0, 0x1)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/github/config_decoder.go:40 +0x748
github.com/github/hub/github.(*configService).Load(0xc00009f598, 0xc0000150e0, 0x1b, 0xc00000cae0, 0x0, 0x0)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/github/config_service.go:42 +0xb1
github.com/github/hub/github.CurrentConfig(0xc00002042a)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/github/config.go:305 +0x117
github.com/github/hub/github.newProject(0xc000020421, 0x8, 0xc00002042a, 0x9, 0xc00002040a, 0x16, 0xc000020400, 0x3, 0x0)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/github/project.go:164 +0x32c
github.com/github/hub/github.NewProjectFromURL(0xc000094400, 0x1, 0x0, 0x0)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/github/project.go:129 +0x12f
github.com/github/hub/github.(*Remote).Project(0xc00009f728, 0x0, 0x0, 0x7323e0)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/github/remote.go:27 +0x33
github.com/github/hub/github.(*GitHubRepo).MainProject(0xc00000c660, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/github/localrepo.go:209 +0xa6
github.com/github/hub/commands.pullRequest(0x9f28c0, 0xc0000d44d0)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/commands/pull_request.go:163 +0xa2
github.com/github/hub/commands.(*Command).Call(0x9f28c0, 0xc0000d44d0, 0xc00007f501, 0xda0000c000086a00)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/commands/commands.go:45 +0x126
github.com/github/hub/commands.(*Runner).Call(0xc00004ae10, 0x9f28c0, 0xc0000d44d0, 0xc, 0xc000086dd8, 0xc000000300, 0xc00007fd40)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/commands/runner.go:115 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc00004ae10, 0x793df8, 0xc00009ff88, 0x4070c0, 0xc00001e0b8)
        /builddir/build/BUILD/hub-2.7.1/src/github.com/github/hub/commands/runner.go:100 +0x3a7
main.main()
        /builddir/build/BUILD/hub-2.7.1/main.go:16 +0x51

Would you like to open an issue? ([Y]es/[N]o/[A]lways/N[e]ver):
```

I have a ~/.config/hub file, that looks like this:

```
<my organization's github hostname>:
  oauth_token: <my token>
  user: <my username>
```

I get the same error with or without the '-h' in the pull-request call. I'm new to git so please be gentle.

Thanks.

**Comment by mislav** [comment]
Hi thanks for reporting! Could you please try the latest release of hub? https://github.com/github/hub/releases

**Comment by mislav** [comment]
I think your `~/.config/hub` should be of this format:

```yml
example.com:
- oauth_token: <my token>
  user: <my username>
```

Note the dash

**Comment by mislav** [comment]
@swechsler Did you find the cause of your issue?

**Comment by ramakrishna61926192** [comment]
If we were to store the credentials in the  hub file, how is  this going to work on a server where lot of users will be using hub to create a pull request.
