### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by smehboub** [github/hub#2101]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x55df0b8d75c0, 0x55df0bab4c20)
	/usr/lib/golang/src/runtime/panic.go:489 +0x2d3
github.com/github/hub/git.WorkdirName(0xc420017d70, 0x26, 0x0, 0x0)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/git/git.go:70 +0xb8
github.com/github/hub/commands.create(0x55df0babb9a0, 0xc42008ec80)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/commands/create.go:66 +0x61
github.com/github/hub/commands.(*Command).Call(0x55df0babb9a0, 0xc42008ec80, 0x7ffe511c20f2, 0x6)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/commands/commands.go:47 +0x142
github.com/github/hub/commands.(*Runner).Call(0xc4200153f0, 0x55df0babb9a0, 0xc42008ec80, 0x6, 0xc420074e98, 0x55df0b5ff7ab, 0xc4200eff18)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/commands/runner.go:108 +0x3b
github.com/github/hub/commands.(*Runner).Execute(0xc4200153f0, 0x55df0b93e6e0, 0x0, 0x0, 0xc)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/commands/runner.go:96 +0x1f8
main.main()
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/main.go:14 +0x53

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.9.5
hub version 2.2.9
```

**Comment by mislav** [comment]
Thank you for reporting! This was fixed in 01c3099abe56a8dcca41e285c11c0f6f860cc338 almost 2 years ago, so be sure to upgrade to the latest version of hub!
