### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by andersonba** [github/hub#2102]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x135d120, 0x1685b50)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522 +0x1b5
github.com/github/hub/commands.transformRemoteArgs(0xc000140300)
	commands/remote.go:108 +0xf01
github.com/github/hub/commands.remote(0x168bd00, 0xc000140300)
	commands/remote.go:53 +0x6b
github.com/github/hub/commands.(*Command).Call(0x168bd00, 0xc000140300, 0xc0000be010, 0x3)
	commands/commands.go:45 +0x7f
github.com/github/hub/commands.callRunnableCommand(0x168bd00, 0xc000140300, 0x7ffeefbff62c, 0x6)
	commands/runner.go:78 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc0000b4040, 0xc0000b8000, 0x7, 0x7, 0xc0000e3f88, 0xc00008a058)
	commands/runner.go:61 +0x3ee
main.main()
	main.go:17 +0x71

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.21.0
hub version 2.11.1
```

**Comment by mislav** [comment]
Thank you for reporting! Any crash is a legitimate bug, so I'm reopening this.
