### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by daveyarwood** [github/hub#2204]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x8ca4a0, 0xc82001a100)
	/home/travis/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:443 +0x4e9
github.com/github/hub/git.WorkdirName(0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/git/git.go:70 +0xf7
github.com/github/hub/commands.create(0xbf2320, 0xc8200a0fa0)
	/tmp/go/src/github.com/github/hub/commands/create.go:66 +0xd6
github.com/github/hub/commands.(*Command).Call(0xbf2320, 0xc8200a0fa0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc820079450, 0xbf2320, 0xc8200a0fa0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:108 +0x5e
github.com/github/hub/commands.(*Runner).Execute(0xc820079450, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:96 +0x1df
main.main()
	/home/travis/gopath/src/github.com/github/hub/main.go:14 +0x50

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.7.4
hub version 2.2.9
```

I ran `git create -d docs.alda.io` and it crashed unexpectedly. Could be some issue with the dots in the repo name?

**Comment by aecdanjun** [comment]
see this #2101

**Comment by daveyarwood** [comment]
Aha! It has been quite a while since I've updated. I'll do that and trust that it's fixed :)
