### ISSUE TITLE
RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObje ct

### ISSUE THREAD

**Issue by BehdadParhizi** [github/hub#2364]
Hi Guys, I got the error below, tried everything, from uninstall/installing numpy and even uninstall/installing python and Anaconda
This problem appeared from nowhere, a few second before this, the code gave me the result OK.
Can anyone help me with this?
 

C:\Users\Administrator\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObje
ct
  return f(*args, **kwds)
No Bottleneck unit testing available.
Traceback (most recent call last):
  File "grid.py", line 1, in <module>
    import numpy as np
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import random
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\random\__init__.py", line 181, in <module>
    from . import _pickle
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 9, in init numpy.random.mtrand
  File "mt19937.pyx", line 1, in init numpy.random.mt19937
  File "bit_generator.pyx", line 40, in init numpy.random.bit_generator
  File "C:\Users\Administrator\Anaconda3\lib\secrets.py", line 20, in <module>
    from random import SystemRandom
  File "C:\Users\Administrator\random.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pandas\core\api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pandas\core\arrays\__init__.py", line 7, in <module>
    from .categorical import Categorical  # noqa: F401
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pandas\core\arrays\categorical.py", line 54, in <module>
    from pandas.core.base import NoNewAttributesMixin, PandasObject, _shared_docs
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pandas\core\base.py", line 159, in <module>
    class SelectionMixin:
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pandas\core\base.py", line 170, in SelectionMixin
    ((builtins.sum, np.sum), (builtins.max, np.max), (builtins.min, np.min))
AttributeError: module 'numpy' has no attribute 'max'

**Comment by mislav** [comment]
Hi it looks like you might be having problem with Anaconda?

This issue tracker is for a project called "hub", which is a command-line tool written in Go. We use neither Python nor Anaconda. I think you should ask elsewhere! Thank you.
