### ISSUE TITLE
conda command unfunctional

### ISSUE THREAD

**Issue by SHIVJITH** [github/hub#2376]
`Traceback (most recent call last):
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\cli\main.py", line 103, in _main
    from ..base.context import context
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\LENOVO\.condarc", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\cli\main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\exceptions.py", line 579, in print_unexpected_error_message
    from .base.context import context
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\LENOVO\.condarc", position 0`

**Comment by mislav** [comment]
This issue tracker is for a project called "hub". It's written in Go and has nothing to do with Anaconda nor Python.
