### ISSUE TITLE
Crash with illegal instruction on old Mac Pro

### ISSUE THREAD

**Issue by Synchro** [github/hub#2509]
**Command attempted:**
`git clone <repo_URL>`

**What happened:**
```
SIGILL: illegal instruction
PC=0x1065340 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc000076ef0 sp=0xc000076ee8 pc=0x1065340
fmt.init()
	/usr/local/Cellar/go/1.14/libexec/src/fmt/scan.go:465 fp=0xc000076ef8 sp=0xc000076ef0 pc=0x10df390
runtime.doInit(0x1687960)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc000076f28 sp=0xc000076ef8 pc=0x1042a1a
runtime.doInit(0x168c1c0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000076f58 sp=0xc000076f28 pc=0x10429e7
runtime.doInit(0x16866a0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000076f88 sp=0xc000076f58 pc=0x10429e7
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc000076fe0 sp=0xc000076f88 pc=0x1035efe
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x1063ae1

rax    0x1687960
rbx    0xb
rcx    0x0
rdx    0x16879b8
rdi    0xc000122210
rsi    0x10df390
rbp    0xc000076f18
rsp    0xc000076ee8
r8     0x11
r9     0x11
r10    0x14631a4
r11    0x1
r12    0xffffffffffffffff
r13    0x22
r14    0x21
r15    0x200
rip    0x1065340
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0
```

**More info:**

**Comment by Synchro** [comment]
This is down to a go bug that breaks go on pre-AVX CPUs, such as on old Mac Pros. See [this bug](https://github.com/golang/go/issues/37478). It will apparently be fixed in go 1.14.1, but until then you can fall back to go 1.13.
