### ISSUE TITLE
!  functions: Upload Error: Server Error. Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by Md-Abdul-Halim-Rafi** [github/hub#2511]
I am having this issue while **deploying firebase function** since **4 days** : 

```D:\MC-Tutorials\NodeJSPrac\fire-funstion-test>firebase deploy

=== Deploying to 'learnee-274b4'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (27.77 KB) for uploading
!  functions: Upload Error: Server Error. Client network socket disconnected before secure TLS connection was established

Error: Server Error. Client network socket disconnected before secure TLS connection was established
```

and my `firebase-debug.log` file is: 

```[debug] [2020-04-01T13:47:28.490Z] ----------------------------------------------------------------------
[debug] [2020-04-01T13:47:28.493Z] Command:       G:\Android\nodejs\node.exe C:\Users\Emahrb Rafi\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2020-04-01T13:47:28.493Z] CLI Version:   7.16.1
[debug] [2020-04-01T13:47:28.494Z] Platform:      win32
[debug] [2020-04-01T13:47:28.494Z] Node Version:  v12.14.0
[debug] [2020-04-01T13:47:28.495Z] Time:          Wed Apr 01 2020 19:47:28 GMT+0600 (Bangladesh Standard Time)
[debug] [2020-04-01T13:47:28.495Z] ----------------------------------------------------------------------
[debug] [2020-04-01T13:47:28.495Z] 
[debug] [2020-04-01T13:47:28.507Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-01T13:47:28.508Z] > authorizing via signed-in user
[debug] [2020-04-01T13:47:28.508Z] [iam] checking project learnee-274b4 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2020-04-01T13:47:28.512Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/learnee-274b4:testIamPermissions  

[debug] [2020-04-01T13:47:30.152Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'learnee-274b4'...
[info] 
[info] i  deploying functions
[debug] [2020-04-01T13:47:33.257Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase-admin": "^8.6.0",
    "firebase-functions": "^3.3.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.1.6"
  },
  "private": true
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2020-04-01T13:47:33.259Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/learnee-274b4/services/cloudfunctions.googleapis.com  
 
[debug] [2020-04-01T13:47:33.260Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/learnee-274b4/services/runtimeconfig.googleapis.com  
 
[debug] [2020-04-01T13:47:36.176Z] <<< HTTP RESPONSE 200
[debug] [2020-04-01T13:47:36.386Z] <<< HTTP RESPONSE 200
[info] +  functions: all necessary APIs are enabled
[debug] [2020-04-01T13:47:36.388Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/learnee-274b4/adminSdkConfig  
 
[debug] [2020-04-01T13:47:36.779Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2020-04-01T13:47:36.784Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/learnee-274b4/configs  
 
[debug] [2020-04-01T13:47:38.583Z] <<< HTTP RESPONSE 200
[info] i  functions: packaged functions (27.77 KB) for uploading
[debug] [2020-04-01T13:47:38.831Z] >>> HTTP REQUEST POST https://cloudfunctions.googleapis.com/v1/projects/learnee-274b4/locations/us-central1/functions:generateUploadUrl  
 
[debug] [2020-04-01T13:47:39.866Z] <<< HTTP RESPONSE 200
[debug] [2020-04-01T13:47:39.867Z] >>> HTTP REQUEST PUT https://storage.googleapis.com/gcf-upload-us-central1-35f545cd-7d29-43c9-8d6a-b598a8fc84de/58068c06-e41d-445f-a5f7-083517d6d259.zip?GoogleAccessId=service-863797571591@gcf-admin-robot.iam.gserviceaccount.com&Expires=1585750662&Signature=j5TlcG8H6P2oUHaZ9UNjMA%2BI%2Bt0V2NEMSE7mLSLo%2F06K0BSUbWea61Ns6hxmZrdmZOWjp2C9EZoVkTQwpp1S8XoyQfl9%2Fkn4ZZVfIa5WY7L8iRSeF1fJQr1Z4CHSaTZS99imi0C4%2F5tTx6Zhpm%2FMDGMbaDh7Bbs%2FXUYTXUd9%2FLG9SP%2BReaz8lzs7gawPe3sMlNbJL%2BgjPchDaPVMFnfLGpEj1Nat1MsT8Vd%2BJGOMsLf19VFy912FZPOk%2FQ4DUvHtGbXLORGY2QJCUSK0b8RYjIqytKx6lskp0CmOXrT5ZNm7L6jJU9kxpisfdGDRN6mE3RqWwmKFimABjA%2BX4m6v%2FA%3D%3D  
 <request body omitted>
[warn] !  functions: Upload Error: Server Error. Client network socket disconnected before secure TLS connection was established
[debug] [2020-04-01T13:47:53.461Z] Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:299:28)
    at TLSSocket.emit (events.js:215:7)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[error] 
[error] Error: Server Error. Client network socket disconnected before secure TLS connection was established

```

**Comment by Saad-IUT** [comment]
I'm also having the same issue here it's been quite a few days now!!

**Comment by Take-T-MC** [comment]
Same here! :(

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go and has nothing to do with firebase nor deployments. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
