### ISSUE TITLE
SIGILL: illegal instruction. Update hub to use Go 1.14.1.

### ISSUE THREAD

**Issue by aryan9600** [github/hub#2512]
**Command attempted:**
`hub --version` 

**What happened:**
There was a severe crash. Error:
```
SIGILL: illegal instruction
PC=0x1065350 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc000093e90 sp=0xc000093e88 pc=0x1065350
crypto/tls.init()
        /usr/local/Cellar/go/1.14/libexec/src/crypto/tls/alert.go:47 fp=0xc000093e98 sp=0xc000093e90 pc=0x1231c10
runtime.doInit(0x168b140)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc000093ec8 sp=0xc000093e98 pc=0x1042a2a
runtime.doInit(0x168b8e0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000093ef8 sp=0xc000093ec8 pc=0x10429f7
runtime.doInit(0x168b280)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000093f28 sp=0xc000093ef8 pc=0x10429f7
runtime.doInit(0x168c1c0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000093f58 sp=0xc000093f28 pc=0x10429f7
runtime.doInit(0x16866a0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000093f88 sp=0xc000093f58 pc=0x10429f7
runtime.main()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc000093fe0 sp=0xc000093f88 pc=0x1035f0e
runtime.goexit()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x1063af1

rax    0x168b140
rbx    0x25
rcx    0x0
rdx    0x168b268
rdi    0xc0000227d0
rsi    0x1231c10
rbp    0xc000093eb8
rsp    0xc000093e88
r8     0x11
r9     0x11
r10    0x14631c4
r11    0x1
r12    0xffffffffffffffff
r13    0x7e
r14    0x7d
r15    0x200
rip    0x1065350
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0

```

**More info:**
I am on the latest hub version. The problem can be found [here](https://github.com/golang/go/issues/37478). I am running MacOS 10.13 on a Macbook Pro 7,1 with a Intel Pentium Core 2 Duo Processor. Updating hub to use Go 1.14.1 should fix this. This affects any Go tool running Go 1.14 on an old Macbook.

**Comment by mislav** [comment]
Thank you for reporting. I'm guessing you installed hub via Homebrew. Does the issue persist if you use a precompiled binary from our releases page? https://github.com/github/hub/releases/latest

**Comment by mrsakryckman** [comment]
Why does my device get shut down and my email say illegal search.

**Comment by aryan9600** [comment]
Thanks, @mislav. Downloading a precompiled binary from the releases pages fixes it!

**Comment by mislav** [comment]
Closing this since it will get resolved the next time we cut a hub release and Homebrew prepares a new bottle.
