### ISSUE TITLE
2020-05-21 02:03:13.487738: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll

### ISSUE THREAD

**Issue by DiptanshuMalviya** [github/hub#2549]
**Command attempted:**
>>> import tensorflow

**What happened:**
I want to download TensorFlow.  But it showing the error of dynamic Successfully Cudart64_101.dll
I download whatever it wants. Cuda 10.0 , Cudnn <=7.6 version 10.0 even I try with 10.1 Cuda and cudnn 7.6 version 10.1 . But still showing the same.
Please give some solution. What basically it needs. 
 

**More info:**
>>> import tensorflow
2020-05-21 02:03:13.487738: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow_core\python\__init__.py", line 95, in <module>
    from tensorflow.python import keras
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow_core\python\keras\models.py", line 22, in <module>
    from tensorflow.python.keras import backend as K
  File "C:\Users\dipta\Anaconda3\envs\am_keras_tf\lib\site-packages\tensorflow_core\python\keras\backend.py", line 5887, in <module>
    assert _image_data_format in {'channels_last', 'channels_first'}
AssertionError

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
