### ISSUE TITLE
Flutter when being run on web shows blank screen.

### ISSUE THREAD

**Issue by jonathanjohn47** [github/hub#2569]
Yes I know this is already encountered problem. But I have gone through hundreds of github issues and nothing worked. I have a previously existing android app project which I want to run on web.
I ran `flutter run -d chrome -v`. It runs, but chrome shows a blank white screen. And the output of `-v` is as follows:

```
[ +179 ms] executing: [D:\AndroidProjects\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +87 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f73f498da1fe4224e29cf9692161575a3d994f8f
[   +1 ms] executing: [D:\AndroidProjects\flutter/] git tag --contains HEAD
[ +356 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.0-1.0.pre
[  +13 ms] executing: [D:\AndroidProjects\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [D:\AndroidProjects\flutter/] git ls-remote --get-url origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +103 ms] executing: [D:\AndroidProjects\flutter/] git rev-parse --abbrev-ref HEAD
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[  +73 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +25 ms] executing: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +77 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +157 ms] Found plugin cloud_firestore at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.6\
[  +12 ms] Found plugin cloud_firestore_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +12 ms] Found plugin file_picker at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.12.0\
[   +8 ms] Found plugin firebase_auth at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[   +5 ms] Found plugin firebase_auth_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.3+1\
[   +4 ms] Found plugin firebase_core at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +4 ms] Found plugin firebase_core_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +4 ms] Found plugin firebase_storage at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.6\
[   +5 ms] Found plugin flutter_downloader at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.4.4\
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +9 ms] Found plugin open_file at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.1\
[   +5 ms] Found plugin path_provider at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +2 ms] Found plugin path_provider_linux at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+1\
[   +2 ms] Found plugin path_provider_macos at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +4 ms] Found plugin permission_handler at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.1\
[  +11 ms] Found plugin shared_preferences at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +3 ms] Found plugin shared_preferences_macos at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +3 ms] Found plugin shared_preferences_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +31 ms] Found plugin workmanager at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.2.2\
[ +130 ms] Found plugin cloud_firestore at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.6\
[   +3 ms] Found plugin cloud_firestore_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +7 ms] Found plugin file_picker at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.12.0\
[   +4 ms] Found plugin firebase_auth at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[   +3 ms] Found plugin firebase_auth_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.3+1\
[   +2 ms] Found plugin firebase_core at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +4 ms] Found plugin firebase_core_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +2 ms] Found plugin firebase_storage at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.6\
[   +4 ms] Found plugin flutter_downloader at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.4.4\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +9 ms] Found plugin open_file at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.1\
[   +7 ms] Found plugin path_provider at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +6 ms] Found plugin path_provider_linux at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+1\
[   +2 ms] Found plugin path_provider_macos at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +4 ms] Found plugin permission_handler at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.1\
[   +6 ms] Found plugin shared_preferences at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +2 ms] Found plugin shared_preferences_macos at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +8 ms] Found plugin shared_preferences_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +12 ms] Found plugin workmanager at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.2.2\
[  +93 ms] Generating D:\Documents\OfficeFiles\Akal_Academy_Final_Apps\akal_academy_parents\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +177 ms] Launching lib\main.dart on Chrome in debug mode...
[ +184 ms] Updating assets
[ +299 ms] Syncing files to device Chrome...
[  +20 ms] Found plugin cloud_firestore at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.6\
[   +3 ms] Found plugin cloud_firestore_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +5 ms] Found plugin file_picker at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.12.0\
[   +5 ms] Found plugin firebase_auth at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[   +4 ms] Found plugin firebase_auth_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.3+1\
[   +3 ms] Found plugin firebase_core at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +4 ms] Found plugin firebase_core_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +4 ms] Found plugin firebase_storage at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.6\
[   +5 ms] Found plugin flutter_downloader at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.4.4\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +6 ms] Found plugin open_file at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.1\
[   +4 ms] Found plugin path_provider at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +2 ms] Found plugin path_provider_linux at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+1\
[   +2 ms] Found plugin path_provider_macos at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +4 ms] Found plugin permission_handler at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.1\
[   +8 ms] Found plugin shared_preferences at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +3 ms] Found plugin shared_preferences_macos at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +4 ms] Found plugin shared_preferences_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +10 ms] Found plugin workmanager at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.2.2\
[  +22 ms] Found plugin cloud_firestore at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.6\
[   +3 ms] Found plugin cloud_firestore_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +8 ms] Found plugin file_picker at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.12.0\
[   +4 ms] Found plugin firebase_auth at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[   +4 ms] Found plugin firebase_auth_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.3+1\
[   +5 ms] Found plugin firebase_core at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +4 ms] Found plugin firebase_core_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +3 ms] Found plugin firebase_storage at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.6\
[   +7 ms] Found plugin flutter_downloader at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_downloader-1.4.4\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +9 ms] Found plugin open_file at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.1\
[   +6 ms] Found plugin path_provider at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +2 ms] Found plugin path_provider_linux at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+1\
[   +4 ms] Found plugin path_provider_macos at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +6 ms] Found plugin permission_handler at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.1\
[   +5 ms] Found plugin shared_preferences at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +1 ms] Found plugin shared_preferences_macos at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +3 ms] Found plugin shared_preferences_web at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +11 ms] Found plugin workmanager at D:\AndroidProjects\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.2.2\
[  +24 ms] Generating D:\Documents\OfficeFiles\Akal_Academy_Final_Apps\akal_academy_parents\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +109 ms] <- reset
[  +14 ms] D:\AndroidProjects\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\AndroidProjects\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\AndroidProjects\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\hp\AppData\Local\Temp\flutter_tools.f39dc8b4\flutter_tool.6b4c55f0\app.dill --libraries-spec file:///D:/AndroidProjects/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-root C:\Users\hp\AppData\Local\Temp\flutter_tools.f39dc8b4\flutter_tools.1065ec2e --filesystem-scheme org-dartlang-app --initialize-from-dill
build\cache.dill.track.dill --platform file:///D:/AndroidProjects/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +16 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+16332 ms] Syncing files to device Chrome... (completed in 16,707ms, longer than expected)
[   +2 ms] Synced 25.8MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[ +463 ms] [CHROME]:
[   +5 ms] [CHROME]:DevTools listening on ws://127.0.0.1:64399/devtools/browser/26106211-b0af-494d-9c74-51a5dac17282
[+10972 ms] Debug service listening on ws://127.0.0.1:64429/79QOg0H0e1E=

[+1159 ms] Debug service listening on ws://127.0.0.1:64429/79QOg0H0e1E=
[   +4 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[   +2 ms] For more information see https://flutter.dev/web
[   +4 ms] �  To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
[  +89 ms] TypeError: Cannot read property 'app' of undefined
               at Object.app$ [as app] (http://localhost:64386/packages/firebase/src/top_level.dart.lib.js:78:56)
               at new cloud_firestore_web.FirestoreWeb.new (http://localhost:64386/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:802:57)
               at Function.registerWith (http://localhost:64386/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:747:71)
               at Object.registerPlugins (http://localhost:64386/packages/akalacademyparents/generated_plugin_registrant.dart.lib.js:17:38)
               at main$ (http://localhost:64386/web_entrypoint.dart.lib.js:15:35)
               at main$.next (<anonymous>)
               at runBody (http://localhost:64386/dart_sdk.js:37126:34)
               at Object._async [as async] (http://localhost:64386/dart_sdk.js:37157:7)
               at main$ (http://localhost:64386/web_entrypoint.dart.lib.js:14:18)
               at http://localhost:64386/main_module.bootstrap.js:17:10
               at Array.forEach (<anonymous>)
               at window.$dartRunMain (http://localhost:64386/main_module.bootstrap.js:16:32)
               at <anonymous>:1:8
               at Object.runMain (http://localhost:64386/dwds/src/injected/client.js:8787:21)
               at http://localhost:64386/dwds/src/injected/client.js:22487:19
               at _wrapJsFunctionForAsync_closure.$protected (http://localhost:64386/dwds/src/injected/client.js:3834:15)
               at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:64386/dwds/src/injected/client.js:11028:12)
               at Object._asyncStartSync (http://localhost:64386/dwds/src/injected/client.js:3798:20)
               at main__closure1.$call$body$main__closure (http://localhost:64386/dwds/src/injected/client.js:22499:16)
               at main__closure1.call$1 (http://localhost:64386/dwds/src/injected/client.js:22426:19)
               at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:64386/dwds/src/injected/client.js:4168:16)
               at _CustomZone.runUnary$2$2 (http://localhost:64386/dwds/src/injected/client.js:12334:39)
               at _CustomZone.runUnaryGuarded$1$2 (http://localhost:64386/dwds/src/injected/client.js:12266:14)
               at _ControllerSubscription._sendData$1 (http://localhost:64386/dwds/src/injected/client.js:11817:19)
               at _DelayedData.perform$1 (http://localhost:64386/dwds/src/injected/client.js:11969:59)
               at _PendingEvents_schedule_closure.call$0 (http://localhost:64386/dwds/src/injected/client.js:12018:14)
               at Object._microtaskLoop (http://localhost:64386/dwds/src/injected/client.js:4001:24)
               at StaticClosure._startMicrotaskLoop (http://localhost:64386/dwds/src/injected/client.js:4007:11)
               at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:64386/dwds/src/injected/client.js:10897:9)
               at invokeClosure (http://localhost:64386/dwds/src/injected/client.js:1205:26)
               at MutationObserver.<anonymous> (http://localhost:64386/dwds/src/injected/client.js:1224:18)
```

My `flutter doctor -v` is:

```
[√] Flutter (Channel dev, 1.20.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
    • Flutter version 1.20.0-1.0.pre at D:\AndroidProjects\flutter
    • Framework revision f73f498da1 (6 days ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at D:\Program Files\IntelliJ\IntelliJ IDEA Community Edition 2019.2.1
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[√] Connected device (3 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106
    • Edge       • edge       • web-javascript • Microsoft Edge 83.0.478.54

! Doctor found issues in 1 category.

```

My `flutter analyze` is:

```
Analyzing akal_academy_parents...

   info - Name non-constant identifiers using lowerCamelCase - lib\misc_classes\questionaire.dart:2:61 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\misc_classes\questionaire.dart:7:7 - non_constant_identifier_names
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method - lib\ui\applyleave.dart:73:8 - must_call_super
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\attendance.dart:38:10 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\attendance.dart:39:10 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\attendance.dart:208:10 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\attendance.dart:214:14 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\dailymarks.dart:17:16 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\dailymarks.dart:18:16 - non_constant_identifier_names
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method - lib\ui\dailymarks.dart:21:8 - must_call_super
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method - lib\ui\home.dart:457:8 - must_call_super
   info - The value of the local variable 'status' isn't used - lib\ui\home.dart:505:41 - unused_local_variable
   info - This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method - lib\ui\profile.dart:61:8 - must_call_super
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Quiz.currentDate, Quiz.testname - lib\ui\quiz.dart:9:7 -
          must_be_immutable
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\quiz.dart:18:56 - non_constant_identifier_names
   info - Avoid using braces in interpolation when not needed - lib\ui\quiz.dart:62:59 - unnecessary_brace_in_string_interps
   info - Avoid using braces in interpolation when not needed - lib\ui\quiz.dart:62:122 - unnecessary_brace_in_string_interps
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\quiz.dart:127:16 - non_constant_identifier_names
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: QuizSelection.selectedDate - lib\ui\quizselection.dart:6:7 -
          must_be_immutable
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\reportcard.dart:34:7 - non_constant_identifier_names
   info - The field doesn't override an inherited getter or setter - lib\ui\reportcard.dart:34:7 - override_on_non_overriding_member
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\reportcard.dart:83:11 - non_constant_identifier_names
   info - This function has a return type of 'FutureOr<FirebaseUser>', but doesn't end with a return statement - lib\ui\reportcard.dart:111:24 - missing_return
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\reportcard.dart:133:12 - non_constant_identifier_names
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SelectAssignmentFile.date - lib\ui\selectassignmentfile.dart:9:7 -
          must_be_immutable
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\selectassignmentfile.dart:73:12 - non_constant_identifier_names

26 issues found. (ran in 21.7s)
```
I am on Windows 10, and have tried running it in all channels.

Here are my `flutter devices`:

```
3 connected devices:
Web Server • web-server • web-javascript • Flutter Tools
Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106
Edge       • edge       • web-javascript • Microsoft Edge 83.0.478.54
```

Where's the problem? Any suggestion?

**Comment by jonathanjohn47** [comment]
Solved the problem. Fixed the index.html file by configuring Firebase for a new web application.
