### ISSUE TITLE
Crash report - Index 1 is out of bound

### ISSUE THREAD

**Issue by tomtaylor** [github/hub#812]
```
$ git checkout -b https://github.com/<private>/<private>/pull/12
```

Results in this:

Error (*errors.errorString): `Index 1 is out of bound`

Stack:

```
goroutine 1 [running]:
github.com/github/hub/commands.(*Args).InsertParam(0xc20805e1b0, 0x1, 0xc2082b5d38, 0x4, 0x4)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/args.go:99 +0x170
github.com/github/hub/commands.transformCheckoutArgs(0xc20805e1b0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/checkout.go:102 +0xd63
github.com/github/hub/commands.checkout(0x6876a0, 0xc20805e1b0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/checkout.go:36 +0x40
github.com/github/hub/commands.(*Command).Call(0x6876a0, 0xc20805e1b0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/commands.go:46 +0x189
github.com/github/hub/commands.(*Runner).Call(0xc20802b120, 0x6876a0, 0xc20805e1b0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/runner.go:89 +0x54
github.com/github/hub/commands.(*Runner).Execute(0xc20802b120, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/runner.go:81 +0x215
main.main()
	/private/tmp/hub-xGkPdT/hub-2.2.0/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Running:

```
$ git version
git version 2.3.0
hub version 2.2.0
```

**Comment by jingweno** [comment]
The correct syntax is `git checkout https://github.com/<private>/<private>/pull/12` without `-b`. But this is indeed a bug that panics about index out of bound.
