### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by yuuki-arc** [github/hub#859]
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
github.com/github/hub/git.gitGetConfig(0xc208081898, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/git/git.go:180 +0x3d6
github.com/github/hub/git.Config(0x47f530, 0x8, 0x0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/git/git.go:162 +0xc6
github.com/github/hub/github.knownGitHubHosts(0xc20801f1a0, 0x2, 0x2)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/github/hosts.go:31 +0x231
github.com/github/hub/github.NewProjectFromURL(0xc2080113b0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/github/project.go:105 +0x4b
github.com/github/hub/github.ParseURL(0x7fff5fbff788, 0xe, 0x1, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/github/url.go:28 +0x89
github.com/github/hub/commands.transformCheckoutArgs(0xc20804e1b0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/checkout.go:54 +0x114
github.com/github/hub/commands.checkout(0x6876a0, 0xc20804e1b0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/checkout.go:36 +0x40
github.com/github/hub/commands.(*Command).Call(0x6876a0, 0xc20804e1b0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/commands.go:46 +0x189
github.com/github/hub/commands.(*Runner).Call(0xc208029120, 0x6876a0, 0xc20804e1b0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/runner.go:89 +0x54
github.com/github/hub/commands.(*Runner).Execute(0xc208029120, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/runner.go:81 +0x215
main.main()
	/private/tmp/hub-xGkPdT/hub-2.2.0/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

**Comment by mislav** [comment]
Closing because of dup of #858
