### ISSUE TITLE
Unable to enter user/pass to get a token

### ISSUE THREAD

**Issue by jay** [github/hub#913]
Windows 7 x64 enterprise
go version go1.4.2 windows/amd64
GNU bash, version 3.1.23(6)-release (i686-pc-msys)
git version 1.9.5.msysgit.1
hub version 2.2.1
hub built from 1e8f4f4 2015-05-22, also tried v2.2.1

I installed hub on this to convert an issue to a pull request. I entered this command
~~~
hub pull-request -b Alexpux:master -h jay:git_fix_depend https://github.com/Alexpux/MSYS2-packages/issues/259
~~~
As expected it wanted my user/pass to get a token. I entered my username and the prompt to enter a password appeared but I did not have any time to respond to it.
~~~
github.com username: jay
github.com password for jay (never stored):
Error creating pull request: Unauthorized (HTTP 401)
Bad credentials
~~~
The second time I tried I was able to enter the password but when I hit enter I got `runtime error: slice bounds out of range`:
~~~
github.com username: jay
github.com password for jay (never stored): runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.getch(0xc082026008)
        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/win.go:37 +0x70f
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.getPasswd(0x300000000, 0x0, 0x0, 0x0)
        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/pass.go:18 +0x126
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.GetPasswd(0x0, 0x0, 0x0)
        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/pass.go:37 +0x45
github.com/github/hub/github.(*Config).PromptForPassword(0xc0820943e0, 0xc08207a299, 0xa, 0xc082002a6d, 0x3, 0x0, 0x0)
        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/github/config.go:123 +0x1f2
github.com/github/hub/github.(*Config).PromptForHost(0xc0820943e0, 0xc08207a299, 0xa, 0x0, 0x0, 0x0)
        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/github/config.go:61 +0x105
github.com/github/hub/commands.pullRequest(0xa9de60, 0xc08202a000)
        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/commands/pull_request.go:93 +0x125
github.com/github/hub/commands.(*Command).Call(0xa9de60, 0xc08202a000, 0x0, 0x0)

        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/commands/commands.go:47 +0x18b
github.com/github/hub/commands.(*Runner).Call(0xc0820031f0, 0xa9de60, 0xc08202a000, 0x0, 0x0, 0x0)
        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/commands/runner.go:90 +0x5b
github.com/github/hub/commands.(*Runner).Execute(0xc0820031f0, 0x0, 0x0, 0x0)
        C:/Users/Internet/AppData/Local/go/src/github.com/github/hub/commands/runner.go:82 +0x21c
main.main()
        X:/j/github/hub/main.go:12 +0x47
~~~

I tried 6 more times (some using v2.2.1) but there was no time to enter a password, same as the first time.

To workaround this issue I made the [~/.config/hub](https://github.com/github/hub/issues/293#issuecomment-13936454) manually and created a personal access token for the oauth.

**Comment by mislav** [comment]
Hi, sorry you're having trouble on Windows. We already have a report in #815 about the bug on Windows that is probably causing your issue. Unfortunately we haven't pinpointed it since then. We will try.

Going to close this as duplicate. In the meantime, I'm glad that you've found a workaround for yourself!
