### ISSUE TITLE
Crash when uploading release assets

### ISSUE THREAD

**Issue by kieranklaassen** [github/hub#932]
Error (runtime.errorCString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 16 [running]:
runtime.panic(0x3e4880, 0x67b6a4)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:248 +0x18d
github.com/github/hub/commands.func·005(0xc2082599c0, 0x34, 0x0, 0x0, 0x7517c8, 0xc2082411d0, 0x0, 0x0)
	/var/folders/1n/w4vl66wx3gs0lfzr466r0vjm0000gp/T/go/src/github.com/github/hub/commands/release.go:166 +0x47
path/filepath.walk(0xc2082410b0, 0x23, 0x7517f0, 0xc20801b360, 0xc208313ad0, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/path/filepath/path.go:364 +0x3fd
path/filepath.walk(0xc2082b5820, 0xf, 0x7517f0, 0xc20828c500, 0xc208313ad0, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/path/filepath/path.go:368 +0x4f5
path/filepath.walk(0xc2082bec10, 0x8, 0x7517f0, 0xc2082af8b0, 0xc208313ad0, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/path/filepath/path.go:368 +0x4f5
path/filepath.walk(0x7fff5fbff756, 0x1, 0x7517f0, 0xc2082caa00, 0xc208313ad0, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/path/filepath/path.go:368 +0x4f5
path/filepath.Walk(0x7fff5fbff756, 0x1, 0xc208313ad0, 0x0, 0x0)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/path/filepath/path.go:390 +0xe5
github.com/github/hub/commands.uploadReleaseAssets(0xc208048268, 0xc208066fc0, 0x7fff5fbff756, 0x1)
	/var/folders/1n/w4vl66wx3gs0lfzr466r0vjm0000gp/T/go/src/github.com/github/hub/commands/release.go:170 +0xe3
github.com/github/hub/commands.func·004(0xc208052760, 0xc2080476c0, 0xc208048268)
	/var/folders/1n/w4vl66wx3gs0lfzr466r0vjm0000gp/T/go/src/github.com/github/hub/commands/release.go:117 +0x334
github.com/github/hub/commands.runInLocalRepo(0xc208313d38)
	/var/folders/1n/w4vl66wx3gs0lfzr466r0vjm0000gp/T/go/src/github.com/github/hub/commands/utils.go:114 +0xc9
github.com/github/hub/commands.createRelease(0x679020, 0xc20803caf0)
	/var/folders/1n/w4vl66wx3gs0lfzr466r0vjm0000gp/T/go/src/github.com/github/hub/commands/release.go:120 +0x154
github.com/github/hub/commands.(*Command).Call(0x678f40, 0xc20803caf0, 0x0, 0x0)
	/var/folders/1n/w4vl66wx3gs0lfzr466r0vjm0000gp/T/go/src/github.com/github/hub/commands/commands.go:46 +0x14d
github.com/github/hub/commands.(*Runner).Call(0xc208048060, 0x678f40, 0xc20803caf0, 0x0, 0x0, 0x0)
	/var/folders/1n/w4vl66wx3gs0lfzr466r0vjm0000gp/T/go/src/github.com/github/hub/commands/runner.go:84 +0x44
github.com/github/hub/commands.(*Runner).Execute(0xc208048060, 0x0, 0x0, 0x0)
	/var/folders/1n/w4vl66wx3gs0lfzr466r0vjm0000gp/T/go/src/github.com/github/hub/commands/runner.go:76 +0x1d1
main.main()
	/private/tmp/hub-vYb0sC/main.go:12 +0x3e

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

**Comment by mislav** [comment]
Thanks for the report and I'm sorry you had trouble. Was this when you were uploading release assets? We'll try to do something about this command.

**Comment by mislav** [comment]
@kieranklaassen The `hub release create` command has been entirely reimplemented since you reported this crash. I'm inclined to think that this shouldn't be a problem anymore if you switch to one of the recent hub 2.3.0-prereleases available for download in the Release section. Thank you!

**Comment by kieranklaassen** [comment]
Thanks, appreciate it! 👍
