### ISSUE TITLE
hub doesn't account for special characters in branch names

### ISSUE THREAD

**Issue by mockdeep** [github/hub#945]
I can check out a branch like:

```sh
$ git checkout -b it\'s_dangerous_to_go_alone
```

But when I try to use `hub` to pull request it I get an error:

```sh
$ hub pull-request
/usr/lib/ruby/1.9.1/shellwords.rb:35:in `block in shellsplit': Unmatched double quote: "rev-list --cherry-pick --right-only --no-merges origin/it's_dangerous_to_go_alone..." (ArgumentError)
	from /usr/lib/ruby/1.9.1/shellwords.rb:33:in `scan'
	from /usr/lib/ruby/1.9.1/shellwords.rb:33:in `shellsplit'
	from /home/fletch/bin/hub:903:in `to_exec'
	from /home/fletch/bin/hub:908:in `command_to_string'
	from /home/fletch/bin/hub:867:in `block in initialize'
	from /home/fletch/bin/hub:885:in `yield'
	from /home/fletch/bin/hub:885:in `default'
	from /home/fletch/bin/hub:885:in `read'
	from /home/fletch/bin/hub:1324:in `rev_list'
	from /home/fletch/bin/hub:1720:in `pull_request'
	from /home/fletch/bin/hub:1586:in `run'
	from /home/fletch/bin/hub:2514:in `initialize'
	from /home/fletch/bin/hub:2518:in `new'
	from /home/fletch/bin/hub:2518:in `execute'
	from /home/fletch/bin/hub:2569:in `<main>
```

**Comment by mislav** [comment]
This was fixed in v1.12.3 (bc4b450b613ba9a79f71ccb3246d87f8e99a1b00), but ideally you should upgrade to newest hub version (v2.2).

**Comment by mockdeep** [comment]
Oh, ha. Cool. So are there upgrade instructions somewhere?

**Comment by mockdeep** [comment]
nm, just downloaded the latest binary.
